// Generated by scripts/generate-battle-dictionaries.mjs. Do not edit manually.
// Sources are local reference files under others/ and are not read at runtime.
import type { DictionaryEntry } from "./types";

export const POKEMON_NAME_DICTIONARY: readonly DictionaryEntry[] = [
  {
    "id": "pokemon:0001",
    "label": "フシギダネ"
  },
  {
    "id": "pokemon:0002",
    "label": "フシギソウ"
  },
  {
    "id": "pokemon:0003",
    "label": "フシギバナ"
  },
  {
    "id": "pokemon:0004",
    "label": "メガフシギバナ"
  },
  {
    "id": "pokemon:0005",
    "label": "ヒトカゲ"
  },
  {
    "id": "pokemon:0006",
    "label": "リザード"
  },
  {
    "id": "pokemon:0007",
    "label": "リザードン"
  },
  {
    "id": "pokemon:0008",
    "label": "メガリザードンX"
  },
  {
    "id": "pokemon:0009",
    "label": "メガリザードンY"
  },
  {
    "id": "pokemon:0010",
    "label": "ゼニガメ"
  },
  {
    "id": "pokemon:0011",
    "label": "カメール"
  },
  {
    "id": "pokemon:0012",
    "label": "カメックス"
  },
  {
    "id": "pokemon:0013",
    "label": "メガカメックス"
  },
  {
    "id": "pokemon:0014",
    "label": "キャタピー"
  },
  {
    "id": "pokemon:0015",
    "label": "トランセル"
  },
  {
    "id": "pokemon:0016",
    "label": "バタフリー"
  },
  {
    "id": "pokemon:0017",
    "label": "ビードル"
  },
  {
    "id": "pokemon:0018",
    "label": "コクーン"
  },
  {
    "id": "pokemon:0019",
    "label": "スピアー"
  },
  {
    "id": "pokemon:0020",
    "label": "メガスピアー"
  },
  {
    "id": "pokemon:0021",
    "label": "ポッポ"
  },
  {
    "id": "pokemon:0022",
    "label": "ピジョン"
  },
  {
    "id": "pokemon:0023",
    "label": "ピジョット"
  },
  {
    "id": "pokemon:0024",
    "label": "メガピジョット"
  },
  {
    "id": "pokemon:0025",
    "label": "コラッタ"
  },
  {
    "id": "pokemon:0026",
    "label": "ラッタ"
  },
  {
    "id": "pokemon:0027",
    "label": "オニスズメ"
  },
  {
    "id": "pokemon:0028",
    "label": "オニドリル"
  },
  {
    "id": "pokemon:0029",
    "label": "アーボ"
  },
  {
    "id": "pokemon:0030",
    "label": "アーボック"
  },
  {
    "id": "pokemon:0031",
    "label": "ピカチュウ"
  },
  {
    "id": "pokemon:0032",
    "label": "ライチュウ"
  },
  {
    "id": "pokemon:0033",
    "label": "メガライチュウX"
  },
  {
    "id": "pokemon:0034",
    "label": "メガライチュウY"
  },
  {
    "id": "pokemon:0035",
    "label": "サンド"
  },
  {
    "id": "pokemon:0036",
    "label": "サンドパン"
  },
  {
    "id": "pokemon:0037",
    "label": "ニドラン"
  },
  {
    "id": "pokemon:0038",
    "label": "ニドラン♀"
  },
  {
    "id": "pokemon:0039",
    "label": "ニドリーナ"
  },
  {
    "id": "pokemon:0040",
    "label": "ニドクイン"
  },
  {
    "id": "pokemon:0041",
    "label": "ニドラン♂"
  },
  {
    "id": "pokemon:0042",
    "label": "ニドリーノ"
  },
  {
    "id": "pokemon:0043",
    "label": "ニドキング"
  },
  {
    "id": "pokemon:0044",
    "label": "ピッピ"
  },
  {
    "id": "pokemon:0045",
    "label": "ピクシー"
  },
  {
    "id": "pokemon:0046",
    "label": "メガピクシー"
  },
  {
    "id": "pokemon:0047",
    "label": "ロコン"
  },
  {
    "id": "pokemon:0048",
    "label": "キュウコン"
  },
  {
    "id": "pokemon:0049",
    "label": "プリン"
  },
  {
    "id": "pokemon:0050",
    "label": "プクリン"
  },
  {
    "id": "pokemon:0051",
    "label": "ズバット"
  },
  {
    "id": "pokemon:0052",
    "label": "ゴルバット"
  },
  {
    "id": "pokemon:0053",
    "label": "ナゾノクサ"
  },
  {
    "id": "pokemon:0054",
    "label": "クサイハナ"
  },
  {
    "id": "pokemon:0055",
    "label": "ラフレシア"
  },
  {
    "id": "pokemon:0056",
    "label": "パラス"
  },
  {
    "id": "pokemon:0057",
    "label": "パラセクト"
  },
  {
    "id": "pokemon:0058",
    "label": "コンパン"
  },
  {
    "id": "pokemon:0059",
    "label": "モルフォン"
  },
  {
    "id": "pokemon:0060",
    "label": "ディグダ"
  },
  {
    "id": "pokemon:0061",
    "label": "ダグトリオ"
  },
  {
    "id": "pokemon:0062",
    "label": "ニャース"
  },
  {
    "id": "pokemon:0063",
    "label": "ペルシアン"
  },
  {
    "id": "pokemon:0064",
    "label": "コダック"
  },
  {
    "id": "pokemon:0065",
    "label": "ゴルダック"
  },
  {
    "id": "pokemon:0066",
    "label": "マンキー"
  },
  {
    "id": "pokemon:0067",
    "label": "オコリザル"
  },
  {
    "id": "pokemon:0068",
    "label": "ガーディ"
  },
  {
    "id": "pokemon:0069",
    "label": "ウインディ"
  },
  {
    "id": "pokemon:0070",
    "label": "ニョロモ"
  },
  {
    "id": "pokemon:0071",
    "label": "ニョロゾ"
  },
  {
    "id": "pokemon:0072",
    "label": "ニョロボン"
  },
  {
    "id": "pokemon:0073",
    "label": "ケーシィ"
  },
  {
    "id": "pokemon:0074",
    "label": "ユンゲラー"
  },
  {
    "id": "pokemon:0075",
    "label": "フーディン"
  },
  {
    "id": "pokemon:0076",
    "label": "メガフーディン"
  },
  {
    "id": "pokemon:0077",
    "label": "ワンリキー"
  },
  {
    "id": "pokemon:0078",
    "label": "ゴーリキー"
  },
  {
    "id": "pokemon:0079",
    "label": "カイリキー"
  },
  {
    "id": "pokemon:0080",
    "label": "マダツボミ"
  },
  {
    "id": "pokemon:0081",
    "label": "ウツドン"
  },
  {
    "id": "pokemon:0082",
    "label": "ウツボット"
  },
  {
    "id": "pokemon:0083",
    "label": "メガウツボット"
  },
  {
    "id": "pokemon:0084",
    "label": "メノクラゲ"
  },
  {
    "id": "pokemon:0085",
    "label": "ドククラゲ"
  },
  {
    "id": "pokemon:0086",
    "label": "イシツブテ"
  },
  {
    "id": "pokemon:0087",
    "label": "ゴローン"
  },
  {
    "id": "pokemon:0088",
    "label": "ゴローニャ"
  },
  {
    "id": "pokemon:0089",
    "label": "ポニータ"
  },
  {
    "id": "pokemon:0090",
    "label": "ギャロップ"
  },
  {
    "id": "pokemon:0091",
    "label": "ヤドン"
  },
  {
    "id": "pokemon:0092",
    "label": "ヤドラン"
  },
  {
    "id": "pokemon:0093",
    "label": "メガヤドラン"
  },
  {
    "id": "pokemon:0094",
    "label": "コイル"
  },
  {
    "id": "pokemon:0095",
    "label": "レアコイル"
  },
  {
    "id": "pokemon:0096",
    "label": "カモネギ"
  },
  {
    "id": "pokemon:0097",
    "label": "ドードー"
  },
  {
    "id": "pokemon:0098",
    "label": "ドードリオ"
  },
  {
    "id": "pokemon:0099",
    "label": "パウワウ"
  },
  {
    "id": "pokemon:0100",
    "label": "ジュゴン"
  },
  {
    "id": "pokemon:0101",
    "label": "ベトベター"
  },
  {
    "id": "pokemon:0102",
    "label": "ベトベトン"
  },
  {
    "id": "pokemon:0103",
    "label": "シェルダー"
  },
  {
    "id": "pokemon:0104",
    "label": "パルシェン"
  },
  {
    "id": "pokemon:0105",
    "label": "ゴース"
  },
  {
    "id": "pokemon:0106",
    "label": "ゴースト"
  },
  {
    "id": "pokemon:0107",
    "label": "ゲンガー"
  },
  {
    "id": "pokemon:0108",
    "label": "メガゲンガー"
  },
  {
    "id": "pokemon:0109",
    "label": "イワーク"
  },
  {
    "id": "pokemon:0110",
    "label": "スリープ"
  },
  {
    "id": "pokemon:0111",
    "label": "スリーパー"
  },
  {
    "id": "pokemon:0112",
    "label": "クラブ"
  },
  {
    "id": "pokemon:0113",
    "label": "キングラー"
  },
  {
    "id": "pokemon:0114",
    "label": "ビリリダマ"
  },
  {
    "id": "pokemon:0115",
    "label": "マルマイン"
  },
  {
    "id": "pokemon:0116",
    "label": "タマタマ"
  },
  {
    "id": "pokemon:0117",
    "label": "ナッシー"
  },
  {
    "id": "pokemon:0118",
    "label": "カラカラ"
  },
  {
    "id": "pokemon:0119",
    "label": "ガラガラ"
  },
  {
    "id": "pokemon:0120",
    "label": "サワムラー"
  },
  {
    "id": "pokemon:0121",
    "label": "エビワラー"
  },
  {
    "id": "pokemon:0122",
    "label": "ベロリンガ"
  },
  {
    "id": "pokemon:0123",
    "label": "ドガース"
  },
  {
    "id": "pokemon:0124",
    "label": "マタドガス"
  },
  {
    "id": "pokemon:0125",
    "label": "サイホーン"
  },
  {
    "id": "pokemon:0126",
    "label": "サイドン"
  },
  {
    "id": "pokemon:0127",
    "label": "ラッキー"
  },
  {
    "id": "pokemon:0128",
    "label": "モンジャラ"
  },
  {
    "id": "pokemon:0129",
    "label": "ガルーラ"
  },
  {
    "id": "pokemon:0130",
    "label": "メガガルーラ"
  },
  {
    "id": "pokemon:0131",
    "label": "タッツー"
  },
  {
    "id": "pokemon:0132",
    "label": "シードラ"
  },
  {
    "id": "pokemon:0133",
    "label": "トサキント"
  },
  {
    "id": "pokemon:0134",
    "label": "アズマオウ"
  },
  {
    "id": "pokemon:0135",
    "label": "ヒトデマン"
  },
  {
    "id": "pokemon:0136",
    "label": "スターミー"
  },
  {
    "id": "pokemon:0137",
    "label": "メガスターミー"
  },
  {
    "id": "pokemon:0138",
    "label": "バリヤード"
  },
  {
    "id": "pokemon:0139",
    "label": "ストライク"
  },
  {
    "id": "pokemon:0140",
    "label": "ルージュラ"
  },
  {
    "id": "pokemon:0141",
    "label": "エレブー"
  },
  {
    "id": "pokemon:0142",
    "label": "ブーバー"
  },
  {
    "id": "pokemon:0143",
    "label": "カイロス"
  },
  {
    "id": "pokemon:0144",
    "label": "メガカイロス"
  },
  {
    "id": "pokemon:0145",
    "label": "ケンタロス"
  },
  {
    "id": "pokemon:0146",
    "label": "コイキング"
  },
  {
    "id": "pokemon:0147",
    "label": "ギャラドス"
  },
  {
    "id": "pokemon:0148",
    "label": "メガギャラドス"
  },
  {
    "id": "pokemon:0149",
    "label": "ラプラス"
  },
  {
    "id": "pokemon:0150",
    "label": "メタモン"
  },
  {
    "id": "pokemon:0151",
    "label": "イーブイ"
  },
  {
    "id": "pokemon:0152",
    "label": "シャワーズ"
  },
  {
    "id": "pokemon:0153",
    "label": "サンダース"
  },
  {
    "id": "pokemon:0154",
    "label": "ブースター"
  },
  {
    "id": "pokemon:0155",
    "label": "ポリゴン"
  },
  {
    "id": "pokemon:0156",
    "label": "オムナイト"
  },
  {
    "id": "pokemon:0157",
    "label": "オムスター"
  },
  {
    "id": "pokemon:0158",
    "label": "カブト"
  },
  {
    "id": "pokemon:0159",
    "label": "カブトプス"
  },
  {
    "id": "pokemon:0160",
    "label": "プテラ"
  },
  {
    "id": "pokemon:0161",
    "label": "メガプテラ"
  },
  {
    "id": "pokemon:0162",
    "label": "カビゴン"
  },
  {
    "id": "pokemon:0163",
    "label": "フリーザー"
  },
  {
    "id": "pokemon:0164",
    "label": "サンダー"
  },
  {
    "id": "pokemon:0165",
    "label": "ファイヤー"
  },
  {
    "id": "pokemon:0166",
    "label": "ミニリュウ"
  },
  {
    "id": "pokemon:0167",
    "label": "ハクリュー"
  },
  {
    "id": "pokemon:0168",
    "label": "カイリュー"
  },
  {
    "id": "pokemon:0169",
    "label": "メガカイリュー"
  },
  {
    "id": "pokemon:0170",
    "label": "ミュウツー"
  },
  {
    "id": "pokemon:0171",
    "label": "メガミュウツーX"
  },
  {
    "id": "pokemon:0172",
    "label": "メガミュウツーY"
  },
  {
    "id": "pokemon:0173",
    "label": "ミュウ"
  },
  {
    "id": "pokemon:0174",
    "label": "チコリータ"
  },
  {
    "id": "pokemon:0175",
    "label": "ベイリーフ"
  },
  {
    "id": "pokemon:0176",
    "label": "メガニウム"
  },
  {
    "id": "pokemon:0177",
    "label": "メガメガニウム"
  },
  {
    "id": "pokemon:0178",
    "label": "ヒノアラシ"
  },
  {
    "id": "pokemon:0179",
    "label": "マグマラシ"
  },
  {
    "id": "pokemon:0180",
    "label": "バクフーン"
  },
  {
    "id": "pokemon:0181",
    "label": "ワニノコ"
  },
  {
    "id": "pokemon:0182",
    "label": "アリゲイツ"
  },
  {
    "id": "pokemon:0183",
    "label": "オーダイル"
  },
  {
    "id": "pokemon:0184",
    "label": "メガオーダイル"
  },
  {
    "id": "pokemon:0185",
    "label": "オタチ"
  },
  {
    "id": "pokemon:0186",
    "label": "オオタチ"
  },
  {
    "id": "pokemon:0187",
    "label": "ホーホー"
  },
  {
    "id": "pokemon:0188",
    "label": "ヨルノズク"
  },
  {
    "id": "pokemon:0189",
    "label": "レディバ"
  },
  {
    "id": "pokemon:0190",
    "label": "レディアン"
  },
  {
    "id": "pokemon:0191",
    "label": "イトマル"
  },
  {
    "id": "pokemon:0192",
    "label": "アリアドス"
  },
  {
    "id": "pokemon:0193",
    "label": "クロバット"
  },
  {
    "id": "pokemon:0194",
    "label": "チョンチー"
  },
  {
    "id": "pokemon:0195",
    "label": "ランターン"
  },
  {
    "id": "pokemon:0196",
    "label": "ピチュー"
  },
  {
    "id": "pokemon:0197",
    "label": "ピィ"
  },
  {
    "id": "pokemon:0198",
    "label": "ププリン"
  },
  {
    "id": "pokemon:0199",
    "label": "トゲピー"
  },
  {
    "id": "pokemon:0200",
    "label": "トゲチック"
  },
  {
    "id": "pokemon:0201",
    "label": "ネイティ"
  },
  {
    "id": "pokemon:0202",
    "label": "ネイティオ"
  },
  {
    "id": "pokemon:0203",
    "label": "メリープ"
  },
  {
    "id": "pokemon:0204",
    "label": "モココ"
  },
  {
    "id": "pokemon:0205",
    "label": "デンリュウ"
  },
  {
    "id": "pokemon:0206",
    "label": "メガデンリュウ"
  },
  {
    "id": "pokemon:0207",
    "label": "キレイハナ"
  },
  {
    "id": "pokemon:0208",
    "label": "マリル"
  },
  {
    "id": "pokemon:0209",
    "label": "マリルリ"
  },
  {
    "id": "pokemon:0210",
    "label": "ウソッキー"
  },
  {
    "id": "pokemon:0211",
    "label": "ニョロトノ"
  },
  {
    "id": "pokemon:0212",
    "label": "ハネッコ"
  },
  {
    "id": "pokemon:0213",
    "label": "ポポッコ"
  },
  {
    "id": "pokemon:0214",
    "label": "ワタッコ"
  },
  {
    "id": "pokemon:0215",
    "label": "エイパム"
  },
  {
    "id": "pokemon:0216",
    "label": "ヒマナッツ"
  },
  {
    "id": "pokemon:0217",
    "label": "キマワリ"
  },
  {
    "id": "pokemon:0218",
    "label": "ヤンヤンマ"
  },
  {
    "id": "pokemon:0219",
    "label": "ウパー"
  },
  {
    "id": "pokemon:0220",
    "label": "ヌオー"
  },
  {
    "id": "pokemon:0221",
    "label": "エーフィ"
  },
  {
    "id": "pokemon:0222",
    "label": "ブラッキー"
  },
  {
    "id": "pokemon:0223",
    "label": "ヤミカラス"
  },
  {
    "id": "pokemon:0224",
    "label": "ヤドキング"
  },
  {
    "id": "pokemon:0225",
    "label": "ムウマ"
  },
  {
    "id": "pokemon:0226",
    "label": "アンノーン"
  },
  {
    "id": "pokemon:0227",
    "label": "ソーナンス"
  },
  {
    "id": "pokemon:0228",
    "label": "キリンリキ"
  },
  {
    "id": "pokemon:0229",
    "label": "クヌギダマ"
  },
  {
    "id": "pokemon:0230",
    "label": "フォレトス"
  },
  {
    "id": "pokemon:0231",
    "label": "ノコッチ"
  },
  {
    "id": "pokemon:0232",
    "label": "グライガー"
  },
  {
    "id": "pokemon:0233",
    "label": "ハガネール"
  },
  {
    "id": "pokemon:0234",
    "label": "メガハガネール"
  },
  {
    "id": "pokemon:0235",
    "label": "ブルー"
  },
  {
    "id": "pokemon:0236",
    "label": "グランブル"
  },
  {
    "id": "pokemon:0237",
    "label": "ハリーセン"
  },
  {
    "id": "pokemon:0238",
    "label": "ハッサム"
  },
  {
    "id": "pokemon:0239",
    "label": "メガハッサム"
  },
  {
    "id": "pokemon:0240",
    "label": "ツボツボ"
  },
  {
    "id": "pokemon:0241",
    "label": "ヘラクロス"
  },
  {
    "id": "pokemon:0242",
    "label": "メガヘラクロス"
  },
  {
    "id": "pokemon:0243",
    "label": "ニューラ"
  },
  {
    "id": "pokemon:0244",
    "label": "ヒメグマ"
  },
  {
    "id": "pokemon:0245",
    "label": "リングマ"
  },
  {
    "id": "pokemon:0246",
    "label": "マグマッグ"
  },
  {
    "id": "pokemon:0247",
    "label": "マグカルゴ"
  },
  {
    "id": "pokemon:0248",
    "label": "ウリムー"
  },
  {
    "id": "pokemon:0249",
    "label": "イノムー"
  },
  {
    "id": "pokemon:0250",
    "label": "サニーゴ"
  },
  {
    "id": "pokemon:0251",
    "label": "テッポウオ"
  },
  {
    "id": "pokemon:0252",
    "label": "オクタン"
  },
  {
    "id": "pokemon:0253",
    "label": "デリバード"
  },
  {
    "id": "pokemon:0254",
    "label": "マンタイン"
  },
  {
    "id": "pokemon:0255",
    "label": "エアームド"
  },
  {
    "id": "pokemon:0256",
    "label": "メガエアームド"
  },
  {
    "id": "pokemon:0257",
    "label": "デルビル"
  },
  {
    "id": "pokemon:0258",
    "label": "ヘルガー"
  },
  {
    "id": "pokemon:0259",
    "label": "メガヘルガー"
  },
  {
    "id": "pokemon:0260",
    "label": "キングドラ"
  },
  {
    "id": "pokemon:0261",
    "label": "ゴマゾウ"
  },
  {
    "id": "pokemon:0262",
    "label": "ドンファン"
  },
  {
    "id": "pokemon:0263",
    "label": "ポリゴン2"
  },
  {
    "id": "pokemon:0264",
    "label": "オドシシ"
  },
  {
    "id": "pokemon:0265",
    "label": "ドーブル"
  },
  {
    "id": "pokemon:0266",
    "label": "バルキー"
  },
  {
    "id": "pokemon:0267",
    "label": "カポエラー"
  },
  {
    "id": "pokemon:0268",
    "label": "ムチュール"
  },
  {
    "id": "pokemon:0269",
    "label": "エレキッド"
  },
  {
    "id": "pokemon:0270",
    "label": "ブビィ"
  },
  {
    "id": "pokemon:0271",
    "label": "ミルタンク"
  },
  {
    "id": "pokemon:0272",
    "label": "ハピナス"
  },
  {
    "id": "pokemon:0273",
    "label": "ライコウ"
  },
  {
    "id": "pokemon:0274",
    "label": "エンテイ"
  },
  {
    "id": "pokemon:0275",
    "label": "スイクン"
  },
  {
    "id": "pokemon:0276",
    "label": "ヨーギラス"
  },
  {
    "id": "pokemon:0277",
    "label": "サナギラス"
  },
  {
    "id": "pokemon:0278",
    "label": "バンギラス"
  },
  {
    "id": "pokemon:0279",
    "label": "メガバンギラス"
  },
  {
    "id": "pokemon:0280",
    "label": "ルギア"
  },
  {
    "id": "pokemon:0281",
    "label": "ホウオウ"
  },
  {
    "id": "pokemon:0282",
    "label": "セレビィ"
  },
  {
    "id": "pokemon:0283",
    "label": "キモリ"
  },
  {
    "id": "pokemon:0284",
    "label": "ジュプトル"
  },
  {
    "id": "pokemon:0285",
    "label": "ジュカイン"
  },
  {
    "id": "pokemon:0286",
    "label": "メガジュカイン"
  },
  {
    "id": "pokemon:0287",
    "label": "アチャモ"
  },
  {
    "id": "pokemon:0288",
    "label": "ワカシャモ"
  },
  {
    "id": "pokemon:0289",
    "label": "バシャーモ"
  },
  {
    "id": "pokemon:0290",
    "label": "メガバシャーモ"
  },
  {
    "id": "pokemon:0291",
    "label": "ミズゴロウ"
  },
  {
    "id": "pokemon:0292",
    "label": "ヌマクロー"
  },
  {
    "id": "pokemon:0293",
    "label": "ラグラージ"
  },
  {
    "id": "pokemon:0294",
    "label": "メガラグラージ"
  },
  {
    "id": "pokemon:0295",
    "label": "ポチエナ"
  },
  {
    "id": "pokemon:0296",
    "label": "グラエナ"
  },
  {
    "id": "pokemon:0297",
    "label": "ジグザグマ"
  },
  {
    "id": "pokemon:0298",
    "label": "マッスグマ"
  },
  {
    "id": "pokemon:0299",
    "label": "ケムッソ"
  },
  {
    "id": "pokemon:0300",
    "label": "カラサリス"
  },
  {
    "id": "pokemon:0301",
    "label": "アゲハント"
  },
  {
    "id": "pokemon:0302",
    "label": "マユルド"
  },
  {
    "id": "pokemon:0303",
    "label": "ドクケイル"
  },
  {
    "id": "pokemon:0304",
    "label": "ハスボー"
  },
  {
    "id": "pokemon:0305",
    "label": "ハスブレロ"
  },
  {
    "id": "pokemon:0306",
    "label": "ルンパッパ"
  },
  {
    "id": "pokemon:0307",
    "label": "タネボー"
  },
  {
    "id": "pokemon:0308",
    "label": "コノハナ"
  },
  {
    "id": "pokemon:0309",
    "label": "ダーテング"
  },
  {
    "id": "pokemon:0310",
    "label": "スバメ"
  },
  {
    "id": "pokemon:0311",
    "label": "オオスバメ"
  },
  {
    "id": "pokemon:0312",
    "label": "キャモメ"
  },
  {
    "id": "pokemon:0313",
    "label": "ペリッパー"
  },
  {
    "id": "pokemon:0314",
    "label": "ラルトス"
  },
  {
    "id": "pokemon:0315",
    "label": "キルリア"
  },
  {
    "id": "pokemon:0316",
    "label": "サーナイト"
  },
  {
    "id": "pokemon:0317",
    "label": "メガサーナイト"
  },
  {
    "id": "pokemon:0318",
    "label": "アメタマ"
  },
  {
    "id": "pokemon:0319",
    "label": "アメモース"
  },
  {
    "id": "pokemon:0320",
    "label": "キノココ"
  },
  {
    "id": "pokemon:0321",
    "label": "キノガッサ"
  },
  {
    "id": "pokemon:0322",
    "label": "ナマケロ"
  },
  {
    "id": "pokemon:0323",
    "label": "ヤルキモノ"
  },
  {
    "id": "pokemon:0324",
    "label": "ケッキング"
  },
  {
    "id": "pokemon:0325",
    "label": "ツチニン"
  },
  {
    "id": "pokemon:0326",
    "label": "テッカニン"
  },
  {
    "id": "pokemon:0327",
    "label": "ヌケニン"
  },
  {
    "id": "pokemon:0328",
    "label": "ゴニョニョ"
  },
  {
    "id": "pokemon:0329",
    "label": "ドゴーム"
  },
  {
    "id": "pokemon:0330",
    "label": "バクオング"
  },
  {
    "id": "pokemon:0331",
    "label": "マクノシタ"
  },
  {
    "id": "pokemon:0332",
    "label": "ハリテヤマ"
  },
  {
    "id": "pokemon:0333",
    "label": "ルリリ"
  },
  {
    "id": "pokemon:0334",
    "label": "ノズパス"
  },
  {
    "id": "pokemon:0335",
    "label": "エネコ"
  },
  {
    "id": "pokemon:0336",
    "label": "エネコロロ"
  },
  {
    "id": "pokemon:0337",
    "label": "ヤミラミ"
  },
  {
    "id": "pokemon:0338",
    "label": "メガヤミラミ"
  },
  {
    "id": "pokemon:0339",
    "label": "クチート"
  },
  {
    "id": "pokemon:0340",
    "label": "メガクチート"
  },
  {
    "id": "pokemon:0341",
    "label": "ココドラ"
  },
  {
    "id": "pokemon:0342",
    "label": "コドラ"
  },
  {
    "id": "pokemon:0343",
    "label": "ボスゴドラ"
  },
  {
    "id": "pokemon:0344",
    "label": "メガボスゴドラ"
  },
  {
    "id": "pokemon:0345",
    "label": "アサナン"
  },
  {
    "id": "pokemon:0346",
    "label": "チャーレム"
  },
  {
    "id": "pokemon:0347",
    "label": "メガチャーレム"
  },
  {
    "id": "pokemon:0348",
    "label": "ラクライ"
  },
  {
    "id": "pokemon:0349",
    "label": "ライボルト"
  },
  {
    "id": "pokemon:0350",
    "label": "メガライボルト"
  },
  {
    "id": "pokemon:0351",
    "label": "プラスル"
  },
  {
    "id": "pokemon:0352",
    "label": "マイナン"
  },
  {
    "id": "pokemon:0353",
    "label": "バルビート"
  },
  {
    "id": "pokemon:0354",
    "label": "イルミーゼ"
  },
  {
    "id": "pokemon:0355",
    "label": "ロゼリア"
  },
  {
    "id": "pokemon:0356",
    "label": "ゴクリン"
  },
  {
    "id": "pokemon:0357",
    "label": "マルノーム"
  },
  {
    "id": "pokemon:0358",
    "label": "キバニア"
  },
  {
    "id": "pokemon:0359",
    "label": "サメハダー"
  },
  {
    "id": "pokemon:0360",
    "label": "メガサメハダー"
  },
  {
    "id": "pokemon:0361",
    "label": "ホエルコ"
  },
  {
    "id": "pokemon:0362",
    "label": "ホエルオー"
  },
  {
    "id": "pokemon:0363",
    "label": "ドンメル"
  },
  {
    "id": "pokemon:0364",
    "label": "バクーダ"
  },
  {
    "id": "pokemon:0365",
    "label": "メガバクーダ"
  },
  {
    "id": "pokemon:0366",
    "label": "コータス"
  },
  {
    "id": "pokemon:0367",
    "label": "バネブー"
  },
  {
    "id": "pokemon:0368",
    "label": "ブーピッグ"
  },
  {
    "id": "pokemon:0369",
    "label": "パッチール"
  },
  {
    "id": "pokemon:0370",
    "label": "ナックラー"
  },
  {
    "id": "pokemon:0371",
    "label": "ビブラーバ"
  },
  {
    "id": "pokemon:0372",
    "label": "フライゴン"
  },
  {
    "id": "pokemon:0373",
    "label": "サボネア"
  },
  {
    "id": "pokemon:0374",
    "label": "ノクタス"
  },
  {
    "id": "pokemon:0375",
    "label": "チルット"
  },
  {
    "id": "pokemon:0376",
    "label": "チルタリス"
  },
  {
    "id": "pokemon:0377",
    "label": "メガチルタリス"
  },
  {
    "id": "pokemon:0378",
    "label": "ザングース"
  },
  {
    "id": "pokemon:0379",
    "label": "ハブネーク"
  },
  {
    "id": "pokemon:0380",
    "label": "ルナトーン"
  },
  {
    "id": "pokemon:0381",
    "label": "ソルロック"
  },
  {
    "id": "pokemon:0382",
    "label": "ドジョッチ"
  },
  {
    "id": "pokemon:0383",
    "label": "ナマズン"
  },
  {
    "id": "pokemon:0384",
    "label": "ヘイガニ"
  },
  {
    "id": "pokemon:0385",
    "label": "シザリガー"
  },
  {
    "id": "pokemon:0386",
    "label": "ヤジロン"
  },
  {
    "id": "pokemon:0387",
    "label": "ネンドール"
  },
  {
    "id": "pokemon:0388",
    "label": "リリーラ"
  },
  {
    "id": "pokemon:0389",
    "label": "ユレイドル"
  },
  {
    "id": "pokemon:0390",
    "label": "アノプス"
  },
  {
    "id": "pokemon:0391",
    "label": "アーマルド"
  },
  {
    "id": "pokemon:0392",
    "label": "ヒンバス"
  },
  {
    "id": "pokemon:0393",
    "label": "ミロカロス"
  },
  {
    "id": "pokemon:0394",
    "label": "ポワルン"
  },
  {
    "id": "pokemon:0395",
    "label": "カクレオン"
  },
  {
    "id": "pokemon:0396",
    "label": "カゲボウズ"
  },
  {
    "id": "pokemon:0397",
    "label": "ジュペッタ"
  },
  {
    "id": "pokemon:0398",
    "label": "メガジュペッタ"
  },
  {
    "id": "pokemon:0399",
    "label": "ヨマワル"
  },
  {
    "id": "pokemon:0400",
    "label": "サマヨール"
  },
  {
    "id": "pokemon:0401",
    "label": "トロピウス"
  },
  {
    "id": "pokemon:0402",
    "label": "チリーン"
  },
  {
    "id": "pokemon:0403",
    "label": "メガチリーン"
  },
  {
    "id": "pokemon:0404",
    "label": "アブソル"
  },
  {
    "id": "pokemon:0405",
    "label": "メガアブソル"
  },
  {
    "id": "pokemon:0406",
    "label": "メガアブソルZ"
  },
  {
    "id": "pokemon:0407",
    "label": "ソーナノ"
  },
  {
    "id": "pokemon:0408",
    "label": "ユキワラシ"
  },
  {
    "id": "pokemon:0409",
    "label": "オニゴーリ"
  },
  {
    "id": "pokemon:0410",
    "label": "メガオニゴーリ"
  },
  {
    "id": "pokemon:0411",
    "label": "タマザラシ"
  },
  {
    "id": "pokemon:0412",
    "label": "トドグラー"
  },
  {
    "id": "pokemon:0413",
    "label": "トドゼルガ"
  },
  {
    "id": "pokemon:0414",
    "label": "パールル"
  },
  {
    "id": "pokemon:0415",
    "label": "ハンテール"
  },
  {
    "id": "pokemon:0416",
    "label": "サクラビス"
  },
  {
    "id": "pokemon:0417",
    "label": "ジーランス"
  },
  {
    "id": "pokemon:0418",
    "label": "ラブカス"
  },
  {
    "id": "pokemon:0419",
    "label": "タツベイ"
  },
  {
    "id": "pokemon:0420",
    "label": "コモルー"
  },
  {
    "id": "pokemon:0421",
    "label": "ボーマンダ"
  },
  {
    "id": "pokemon:0422",
    "label": "メガボーマンダ"
  },
  {
    "id": "pokemon:0423",
    "label": "ダンバル"
  },
  {
    "id": "pokemon:0424",
    "label": "メタング"
  },
  {
    "id": "pokemon:0425",
    "label": "メタグロス"
  },
  {
    "id": "pokemon:0426",
    "label": "メガメタグロス"
  },
  {
    "id": "pokemon:0427",
    "label": "レジロック"
  },
  {
    "id": "pokemon:0428",
    "label": "レジアイス"
  },
  {
    "id": "pokemon:0429",
    "label": "レジスチル"
  },
  {
    "id": "pokemon:0430",
    "label": "ラティアス"
  },
  {
    "id": "pokemon:0431",
    "label": "メガラティアス"
  },
  {
    "id": "pokemon:0432",
    "label": "ラティオス"
  },
  {
    "id": "pokemon:0433",
    "label": "メガラティオス"
  },
  {
    "id": "pokemon:0434",
    "label": "カイオーガ"
  },
  {
    "id": "pokemon:0435",
    "label": "ゲンシカイオーガ"
  },
  {
    "id": "pokemon:0436",
    "label": "グラードン"
  },
  {
    "id": "pokemon:0437",
    "label": "ゲンシグラードン"
  },
  {
    "id": "pokemon:0438",
    "label": "レックウザ"
  },
  {
    "id": "pokemon:0439",
    "label": "メガレックウザ"
  },
  {
    "id": "pokemon:0440",
    "label": "ジラーチ"
  },
  {
    "id": "pokemon:0441",
    "label": "デオキシス"
  },
  {
    "id": "pokemon:0442",
    "label": "ナエトル"
  },
  {
    "id": "pokemon:0443",
    "label": "ハヤシガメ"
  },
  {
    "id": "pokemon:0444",
    "label": "ドダイトス"
  },
  {
    "id": "pokemon:0445",
    "label": "ヒコザル"
  },
  {
    "id": "pokemon:0446",
    "label": "モウカザル"
  },
  {
    "id": "pokemon:0447",
    "label": "ゴウカザル"
  },
  {
    "id": "pokemon:0448",
    "label": "ポッチャマ"
  },
  {
    "id": "pokemon:0449",
    "label": "ポッタイシ"
  },
  {
    "id": "pokemon:0450",
    "label": "エンペルト"
  },
  {
    "id": "pokemon:0451",
    "label": "ムックル"
  },
  {
    "id": "pokemon:0452",
    "label": "ムクバード"
  },
  {
    "id": "pokemon:0453",
    "label": "ムクホーク"
  },
  {
    "id": "pokemon:0454",
    "label": "メガムクホーク"
  },
  {
    "id": "pokemon:0455",
    "label": "ビッパ"
  },
  {
    "id": "pokemon:0456",
    "label": "ビーダル"
  },
  {
    "id": "pokemon:0457",
    "label": "コロボーシ"
  },
  {
    "id": "pokemon:0458",
    "label": "コロトック"
  },
  {
    "id": "pokemon:0459",
    "label": "コリンク"
  },
  {
    "id": "pokemon:0460",
    "label": "ルクシオ"
  },
  {
    "id": "pokemon:0461",
    "label": "レントラー"
  },
  {
    "id": "pokemon:0462",
    "label": "スボミー"
  },
  {
    "id": "pokemon:0463",
    "label": "ロズレイド"
  },
  {
    "id": "pokemon:0464",
    "label": "ズガイドス"
  },
  {
    "id": "pokemon:0465",
    "label": "ラムパルド"
  },
  {
    "id": "pokemon:0466",
    "label": "タテトプス"
  },
  {
    "id": "pokemon:0467",
    "label": "トリデプス"
  },
  {
    "id": "pokemon:0468",
    "label": "ミノムッチ"
  },
  {
    "id": "pokemon:0469",
    "label": "ミノマダム"
  },
  {
    "id": "pokemon:0470",
    "label": "ガーメイル"
  },
  {
    "id": "pokemon:0471",
    "label": "ミツハニー"
  },
  {
    "id": "pokemon:0472",
    "label": "ビークイン"
  },
  {
    "id": "pokemon:0473",
    "label": "パチリス"
  },
  {
    "id": "pokemon:0474",
    "label": "ブイゼル"
  },
  {
    "id": "pokemon:0475",
    "label": "フローゼル"
  },
  {
    "id": "pokemon:0476",
    "label": "チェリンボ"
  },
  {
    "id": "pokemon:0477",
    "label": "チェリム"
  },
  {
    "id": "pokemon:0478",
    "label": "カラナクシ"
  },
  {
    "id": "pokemon:0479",
    "label": "トリトドン"
  },
  {
    "id": "pokemon:0480",
    "label": "エテボース"
  },
  {
    "id": "pokemon:0481",
    "label": "フワンテ"
  },
  {
    "id": "pokemon:0482",
    "label": "フワライド"
  },
  {
    "id": "pokemon:0483",
    "label": "ミミロル"
  },
  {
    "id": "pokemon:0484",
    "label": "ミミロップ"
  },
  {
    "id": "pokemon:0485",
    "label": "メガミミロップ"
  },
  {
    "id": "pokemon:0486",
    "label": "ムウマージ"
  },
  {
    "id": "pokemon:0487",
    "label": "ドンカラス"
  },
  {
    "id": "pokemon:0488",
    "label": "ニャルマー"
  },
  {
    "id": "pokemon:0489",
    "label": "ブニャット"
  },
  {
    "id": "pokemon:0490",
    "label": "リーシャン"
  },
  {
    "id": "pokemon:0491",
    "label": "スカンプー"
  },
  {
    "id": "pokemon:0492",
    "label": "スカタンク"
  },
  {
    "id": "pokemon:0493",
    "label": "ドーミラー"
  },
  {
    "id": "pokemon:0494",
    "label": "ドータクン"
  },
  {
    "id": "pokemon:0495",
    "label": "ウソハチ"
  },
  {
    "id": "pokemon:0496",
    "label": "マネネ"
  },
  {
    "id": "pokemon:0497",
    "label": "ピンプク"
  },
  {
    "id": "pokemon:0498",
    "label": "ペラップ"
  },
  {
    "id": "pokemon:0499",
    "label": "ミカルゲ"
  },
  {
    "id": "pokemon:0500",
    "label": "フカマル"
  },
  {
    "id": "pokemon:0501",
    "label": "ガバイト"
  },
  {
    "id": "pokemon:0502",
    "label": "ガブリアス"
  },
  {
    "id": "pokemon:0503",
    "label": "メガガブリアス"
  },
  {
    "id": "pokemon:0504",
    "label": "メガガブリアスZ"
  },
  {
    "id": "pokemon:0505",
    "label": "ゴンベ"
  },
  {
    "id": "pokemon:0506",
    "label": "リオル"
  },
  {
    "id": "pokemon:0507",
    "label": "ルカリオ"
  },
  {
    "id": "pokemon:0508",
    "label": "メガルカリオ"
  },
  {
    "id": "pokemon:0509",
    "label": "メガルカリオZ"
  },
  {
    "id": "pokemon:0510",
    "label": "ヒポポタス"
  },
  {
    "id": "pokemon:0511",
    "label": "カバルドン"
  },
  {
    "id": "pokemon:0512",
    "label": "スコルピ"
  },
  {
    "id": "pokemon:0513",
    "label": "ドラピオン"
  },
  {
    "id": "pokemon:0514",
    "label": "グレッグル"
  },
  {
    "id": "pokemon:0515",
    "label": "ドクロッグ"
  },
  {
    "id": "pokemon:0516",
    "label": "マスキッパ"
  },
  {
    "id": "pokemon:0517",
    "label": "ケイコウオ"
  },
  {
    "id": "pokemon:0518",
    "label": "ネオラント"
  },
  {
    "id": "pokemon:0519",
    "label": "タマンタ"
  },
  {
    "id": "pokemon:0520",
    "label": "ユキカブリ"
  },
  {
    "id": "pokemon:0521",
    "label": "ユキノオー"
  },
  {
    "id": "pokemon:0522",
    "label": "メガユキノオー"
  },
  {
    "id": "pokemon:0523",
    "label": "マニューラ"
  },
  {
    "id": "pokemon:0524",
    "label": "ジバコイル"
  },
  {
    "id": "pokemon:0525",
    "label": "ベロベルト"
  },
  {
    "id": "pokemon:0526",
    "label": "ドサイドン"
  },
  {
    "id": "pokemon:0527",
    "label": "モジャンボ"
  },
  {
    "id": "pokemon:0528",
    "label": "エレキブル"
  },
  {
    "id": "pokemon:0529",
    "label": "ブーバーン"
  },
  {
    "id": "pokemon:0530",
    "label": "トゲキッス"
  },
  {
    "id": "pokemon:0531",
    "label": "メガヤンマ"
  },
  {
    "id": "pokemon:0532",
    "label": "リーフィア"
  },
  {
    "id": "pokemon:0533",
    "label": "グレイシア"
  },
  {
    "id": "pokemon:0534",
    "label": "グライオン"
  },
  {
    "id": "pokemon:0535",
    "label": "マンムー"
  },
  {
    "id": "pokemon:0536",
    "label": "ポリゴンZ"
  },
  {
    "id": "pokemon:0537",
    "label": "エルレイド"
  },
  {
    "id": "pokemon:0538",
    "label": "メガエルレイド"
  },
  {
    "id": "pokemon:0539",
    "label": "ダイノーズ"
  },
  {
    "id": "pokemon:0540",
    "label": "ヨノワール"
  },
  {
    "id": "pokemon:0541",
    "label": "ユキメノコ"
  },
  {
    "id": "pokemon:0542",
    "label": "メガユキメノコ"
  },
  {
    "id": "pokemon:0543",
    "label": "ロトム"
  },
  {
    "id": "pokemon:0544",
    "label": "ヒートロトム"
  },
  {
    "id": "pokemon:0545",
    "label": "ウォッシュロトム"
  },
  {
    "id": "pokemon:0546",
    "label": "フロストロトム"
  },
  {
    "id": "pokemon:0547",
    "label": "スピンロトム"
  },
  {
    "id": "pokemon:0548",
    "label": "カットロトム"
  },
  {
    "id": "pokemon:0549",
    "label": "ユクシー"
  },
  {
    "id": "pokemon:0550",
    "label": "エムリット"
  },
  {
    "id": "pokemon:0551",
    "label": "アグノム"
  },
  {
    "id": "pokemon:0552",
    "label": "ディアルガ"
  },
  {
    "id": "pokemon:0553",
    "label": "パルキア"
  },
  {
    "id": "pokemon:0554",
    "label": "ヒードラン"
  },
  {
    "id": "pokemon:0555",
    "label": "メガヒードラン"
  },
  {
    "id": "pokemon:0556",
    "label": "レジギガス"
  },
  {
    "id": "pokemon:0557",
    "label": "ギラティナ"
  },
  {
    "id": "pokemon:0558",
    "label": "クレセリア"
  },
  {
    "id": "pokemon:0559",
    "label": "フィオネ"
  },
  {
    "id": "pokemon:0560",
    "label": "マナフィ"
  },
  {
    "id": "pokemon:0561",
    "label": "ダークライ"
  },
  {
    "id": "pokemon:0562",
    "label": "メガダークライ"
  },
  {
    "id": "pokemon:0563",
    "label": "シェイミ"
  },
  {
    "id": "pokemon:0564",
    "label": "アルセウス"
  },
  {
    "id": "pokemon:0565",
    "label": "ビクティニ"
  },
  {
    "id": "pokemon:0566",
    "label": "ツタージャ"
  },
  {
    "id": "pokemon:0567",
    "label": "ジャノビー"
  },
  {
    "id": "pokemon:0568",
    "label": "ジャローダ"
  },
  {
    "id": "pokemon:0569",
    "label": "ポカブ"
  },
  {
    "id": "pokemon:0570",
    "label": "チャオブー"
  },
  {
    "id": "pokemon:0571",
    "label": "エンブオー"
  },
  {
    "id": "pokemon:0572",
    "label": "メガエンブオー"
  },
  {
    "id": "pokemon:0573",
    "label": "ミジュマル"
  },
  {
    "id": "pokemon:0574",
    "label": "フタチマル"
  },
  {
    "id": "pokemon:0575",
    "label": "ダイケンキ"
  },
  {
    "id": "pokemon:0576",
    "label": "ミネズミ"
  },
  {
    "id": "pokemon:0577",
    "label": "ミルホッグ"
  },
  {
    "id": "pokemon:0578",
    "label": "ヨーテリー"
  },
  {
    "id": "pokemon:0579",
    "label": "ハーデリア"
  },
  {
    "id": "pokemon:0580",
    "label": "ムーランド"
  },
  {
    "id": "pokemon:0581",
    "label": "チョロネコ"
  },
  {
    "id": "pokemon:0582",
    "label": "レパルダス"
  },
  {
    "id": "pokemon:0583",
    "label": "ヤナップ"
  },
  {
    "id": "pokemon:0584",
    "label": "ヤナッキー"
  },
  {
    "id": "pokemon:0585",
    "label": "バオップ"
  },
  {
    "id": "pokemon:0586",
    "label": "バオッキー"
  },
  {
    "id": "pokemon:0587",
    "label": "ヒヤップ"
  },
  {
    "id": "pokemon:0588",
    "label": "ヒヤッキー"
  },
  {
    "id": "pokemon:0589",
    "label": "ムンナ"
  },
  {
    "id": "pokemon:0590",
    "label": "ムシャーナ"
  },
  {
    "id": "pokemon:0591",
    "label": "マメパト"
  },
  {
    "id": "pokemon:0592",
    "label": "ハトーボー"
  },
  {
    "id": "pokemon:0593",
    "label": "ケンホロウ"
  },
  {
    "id": "pokemon:0594",
    "label": "シママ"
  },
  {
    "id": "pokemon:0595",
    "label": "ゼブライカ"
  },
  {
    "id": "pokemon:0596",
    "label": "ダンゴロ"
  },
  {
    "id": "pokemon:0597",
    "label": "ガントル"
  },
  {
    "id": "pokemon:0598",
    "label": "ギガイアス"
  },
  {
    "id": "pokemon:0599",
    "label": "コロモリ"
  },
  {
    "id": "pokemon:0600",
    "label": "ココロモリ"
  },
  {
    "id": "pokemon:0601",
    "label": "モグリュー"
  },
  {
    "id": "pokemon:0602",
    "label": "ドリュウズ"
  },
  {
    "id": "pokemon:0603",
    "label": "メガドリュウズ"
  },
  {
    "id": "pokemon:0604",
    "label": "タブンネ"
  },
  {
    "id": "pokemon:0605",
    "label": "メガタブンネ"
  },
  {
    "id": "pokemon:0606",
    "label": "ドッコラー"
  },
  {
    "id": "pokemon:0607",
    "label": "ドテッコツ"
  },
  {
    "id": "pokemon:0608",
    "label": "ローブシン"
  },
  {
    "id": "pokemon:0609",
    "label": "オタマロ"
  },
  {
    "id": "pokemon:0610",
    "label": "ガマガル"
  },
  {
    "id": "pokemon:0611",
    "label": "ガマゲロゲ"
  },
  {
    "id": "pokemon:0612",
    "label": "ナゲキ"
  },
  {
    "id": "pokemon:0613",
    "label": "ダゲキ"
  },
  {
    "id": "pokemon:0614",
    "label": "クルミル"
  },
  {
    "id": "pokemon:0615",
    "label": "クルマユ"
  },
  {
    "id": "pokemon:0616",
    "label": "ハハコモリ"
  },
  {
    "id": "pokemon:0617",
    "label": "フシデ"
  },
  {
    "id": "pokemon:0618",
    "label": "ホイーガ"
  },
  {
    "id": "pokemon:0619",
    "label": "ペンドラー"
  },
  {
    "id": "pokemon:0620",
    "label": "メガペンドラー"
  },
  {
    "id": "pokemon:0621",
    "label": "モンメン"
  },
  {
    "id": "pokemon:0622",
    "label": "エルフーン"
  },
  {
    "id": "pokemon:0623",
    "label": "チュリネ"
  },
  {
    "id": "pokemon:0624",
    "label": "ドレディア"
  },
  {
    "id": "pokemon:0625",
    "label": "バスラオ"
  },
  {
    "id": "pokemon:0626",
    "label": "メグロコ"
  },
  {
    "id": "pokemon:0627",
    "label": "ワルビル"
  },
  {
    "id": "pokemon:0628",
    "label": "ワルビアル"
  },
  {
    "id": "pokemon:0629",
    "label": "ダルマッカ"
  },
  {
    "id": "pokemon:0630",
    "label": "ヒヒダルマ"
  },
  {
    "id": "pokemon:0631",
    "label": "マラカッチ"
  },
  {
    "id": "pokemon:0632",
    "label": "イシズマイ"
  },
  {
    "id": "pokemon:0633",
    "label": "イワパレス"
  },
  {
    "id": "pokemon:0634",
    "label": "ズルッグ"
  },
  {
    "id": "pokemon:0635",
    "label": "ズルズキン"
  },
  {
    "id": "pokemon:0636",
    "label": "メガズルズキン"
  },
  {
    "id": "pokemon:0637",
    "label": "シンボラー"
  },
  {
    "id": "pokemon:0638",
    "label": "デスマス"
  },
  {
    "id": "pokemon:0639",
    "label": "デスカーン"
  },
  {
    "id": "pokemon:0640",
    "label": "プロトーガ"
  },
  {
    "id": "pokemon:0641",
    "label": "アバゴーラ"
  },
  {
    "id": "pokemon:0642",
    "label": "アーケン"
  },
  {
    "id": "pokemon:0643",
    "label": "アーケオス"
  },
  {
    "id": "pokemon:0644",
    "label": "ヤブクロン"
  },
  {
    "id": "pokemon:0645",
    "label": "ダストダス"
  },
  {
    "id": "pokemon:0646",
    "label": "ゾロア"
  },
  {
    "id": "pokemon:0647",
    "label": "ゾロアーク"
  },
  {
    "id": "pokemon:0648",
    "label": "チラーミィ"
  },
  {
    "id": "pokemon:0649",
    "label": "チラチーノ"
  },
  {
    "id": "pokemon:0650",
    "label": "ゴチム"
  },
  {
    "id": "pokemon:0651",
    "label": "ゴチミル"
  },
  {
    "id": "pokemon:0652",
    "label": "ゴチルゼル"
  },
  {
    "id": "pokemon:0653",
    "label": "ユニラン"
  },
  {
    "id": "pokemon:0654",
    "label": "ダブラン"
  },
  {
    "id": "pokemon:0655",
    "label": "ランクルス"
  },
  {
    "id": "pokemon:0656",
    "label": "コアルヒー"
  },
  {
    "id": "pokemon:0657",
    "label": "スワンナ"
  },
  {
    "id": "pokemon:0658",
    "label": "バニプッチ"
  },
  {
    "id": "pokemon:0659",
    "label": "バニリッチ"
  },
  {
    "id": "pokemon:0660",
    "label": "バイバニラ"
  },
  {
    "id": "pokemon:0661",
    "label": "シキジカ"
  },
  {
    "id": "pokemon:0662",
    "label": "メブキジカ"
  },
  {
    "id": "pokemon:0663",
    "label": "エモンガ"
  },
  {
    "id": "pokemon:0664",
    "label": "カブルモ"
  },
  {
    "id": "pokemon:0665",
    "label": "シュバルゴ"
  },
  {
    "id": "pokemon:0666",
    "label": "タマゲタケ"
  },
  {
    "id": "pokemon:0667",
    "label": "モロバレル"
  },
  {
    "id": "pokemon:0668",
    "label": "プルリル"
  },
  {
    "id": "pokemon:0669",
    "label": "ブルンゲル"
  },
  {
    "id": "pokemon:0670",
    "label": "ママンボウ"
  },
  {
    "id": "pokemon:0671",
    "label": "バチュル"
  },
  {
    "id": "pokemon:0672",
    "label": "デンチュラ"
  },
  {
    "id": "pokemon:0673",
    "label": "テッシード"
  },
  {
    "id": "pokemon:0674",
    "label": "ナットレイ"
  },
  {
    "id": "pokemon:0675",
    "label": "ギアル"
  },
  {
    "id": "pokemon:0676",
    "label": "ギギアル"
  },
  {
    "id": "pokemon:0677",
    "label": "ギギギアル"
  },
  {
    "id": "pokemon:0678",
    "label": "シビシラス"
  },
  {
    "id": "pokemon:0679",
    "label": "シビビール"
  },
  {
    "id": "pokemon:0680",
    "label": "シビルドン"
  },
  {
    "id": "pokemon:0681",
    "label": "メガシビルドン"
  },
  {
    "id": "pokemon:0682",
    "label": "リグレー"
  },
  {
    "id": "pokemon:0683",
    "label": "オーベム"
  },
  {
    "id": "pokemon:0684",
    "label": "ヒトモシ"
  },
  {
    "id": "pokemon:0685",
    "label": "ランプラー"
  },
  {
    "id": "pokemon:0686",
    "label": "シャンデラ"
  },
  {
    "id": "pokemon:0687",
    "label": "メガシャンデラ"
  },
  {
    "id": "pokemon:0688",
    "label": "キバゴ"
  },
  {
    "id": "pokemon:0689",
    "label": "オノンド"
  },
  {
    "id": "pokemon:0690",
    "label": "オノノクス"
  },
  {
    "id": "pokemon:0691",
    "label": "クマシュン"
  },
  {
    "id": "pokemon:0692",
    "label": "ツンベアー"
  },
  {
    "id": "pokemon:0693",
    "label": "フリージオ"
  },
  {
    "id": "pokemon:0694",
    "label": "チョボマキ"
  },
  {
    "id": "pokemon:0695",
    "label": "アギルダー"
  },
  {
    "id": "pokemon:0696",
    "label": "マッギョ"
  },
  {
    "id": "pokemon:0697",
    "label": "コジョフー"
  },
  {
    "id": "pokemon:0698",
    "label": "コジョンド"
  },
  {
    "id": "pokemon:0699",
    "label": "クリムガン"
  },
  {
    "id": "pokemon:0700",
    "label": "ゴビット"
  },
  {
    "id": "pokemon:0701",
    "label": "ゴルーグ"
  },
  {
    "id": "pokemon:0702",
    "label": "メガゴルーグ"
  },
  {
    "id": "pokemon:0703",
    "label": "コマタナ"
  },
  {
    "id": "pokemon:0704",
    "label": "キリキザン"
  },
  {
    "id": "pokemon:0705",
    "label": "バッフロン"
  },
  {
    "id": "pokemon:0706",
    "label": "ワシボン"
  },
  {
    "id": "pokemon:0707",
    "label": "ウォーグル"
  },
  {
    "id": "pokemon:0708",
    "label": "バルチャイ"
  },
  {
    "id": "pokemon:0709",
    "label": "バルジーナ"
  },
  {
    "id": "pokemon:0710",
    "label": "クイタラン"
  },
  {
    "id": "pokemon:0711",
    "label": "アイアント"
  },
  {
    "id": "pokemon:0712",
    "label": "モノズ"
  },
  {
    "id": "pokemon:0713",
    "label": "ジヘッド"
  },
  {
    "id": "pokemon:0714",
    "label": "サザンドラ"
  },
  {
    "id": "pokemon:0715",
    "label": "メラルバ"
  },
  {
    "id": "pokemon:0716",
    "label": "ウルガモス"
  },
  {
    "id": "pokemon:0717",
    "label": "コバルオン"
  },
  {
    "id": "pokemon:0718",
    "label": "テラキオン"
  },
  {
    "id": "pokemon:0719",
    "label": "ビリジオン"
  },
  {
    "id": "pokemon:0720",
    "label": "トルネロス"
  },
  {
    "id": "pokemon:0721",
    "label": "ボルトロス"
  },
  {
    "id": "pokemon:0722",
    "label": "レシラム"
  },
  {
    "id": "pokemon:0723",
    "label": "ゼクロム"
  },
  {
    "id": "pokemon:0724",
    "label": "ランドロス"
  },
  {
    "id": "pokemon:0725",
    "label": "キュレム"
  },
  {
    "id": "pokemon:0726",
    "label": "ホワイトキュレム"
  },
  {
    "id": "pokemon:0727",
    "label": "ブラックキュレム"
  },
  {
    "id": "pokemon:0728",
    "label": "ケルディオ"
  },
  {
    "id": "pokemon:0729",
    "label": "メロエッタ"
  },
  {
    "id": "pokemon:0730",
    "label": "ゲノセクト"
  },
  {
    "id": "pokemon:0731",
    "label": "ハリマロン"
  },
  {
    "id": "pokemon:0732",
    "label": "ハリボーグ"
  },
  {
    "id": "pokemon:0733",
    "label": "ブリガロン"
  },
  {
    "id": "pokemon:0734",
    "label": "メガブリガロン"
  },
  {
    "id": "pokemon:0735",
    "label": "フォッコ"
  },
  {
    "id": "pokemon:0736",
    "label": "テールナー"
  },
  {
    "id": "pokemon:0737",
    "label": "マフォクシー"
  },
  {
    "id": "pokemon:0738",
    "label": "メガマフォクシー"
  },
  {
    "id": "pokemon:0739",
    "label": "ケロマツ"
  },
  {
    "id": "pokemon:0740",
    "label": "ゲコガシラ"
  },
  {
    "id": "pokemon:0741",
    "label": "ゲッコウガ"
  },
  {
    "id": "pokemon:0742",
    "label": "メガゲッコウガ"
  },
  {
    "id": "pokemon:0743",
    "label": "ホルビー"
  },
  {
    "id": "pokemon:0744",
    "label": "ホルード"
  },
  {
    "id": "pokemon:0745",
    "label": "ヤヤコマ"
  },
  {
    "id": "pokemon:0746",
    "label": "ヒノヤコマ"
  },
  {
    "id": "pokemon:0747",
    "label": "ファイアロー"
  },
  {
    "id": "pokemon:0748",
    "label": "コフキムシ"
  },
  {
    "id": "pokemon:0749",
    "label": "コフーライ"
  },
  {
    "id": "pokemon:0750",
    "label": "ビビヨン"
  },
  {
    "id": "pokemon:0751",
    "label": "シシコ"
  },
  {
    "id": "pokemon:0752",
    "label": "カエンジシ"
  },
  {
    "id": "pokemon:0753",
    "label": "メガカエンジシ"
  },
  {
    "id": "pokemon:0754",
    "label": "フラベベ"
  },
  {
    "id": "pokemon:0755",
    "label": "フラエッテ"
  },
  {
    "id": "pokemon:0756",
    "label": "メガフラエッテ"
  },
  {
    "id": "pokemon:0757",
    "label": "フラージェス"
  },
  {
    "id": "pokemon:0758",
    "label": "メェークル"
  },
  {
    "id": "pokemon:0759",
    "label": "ゴーゴート"
  },
  {
    "id": "pokemon:0760",
    "label": "ヤンチャム"
  },
  {
    "id": "pokemon:0761",
    "label": "ゴロンダ"
  },
  {
    "id": "pokemon:0762",
    "label": "トリミアン"
  },
  {
    "id": "pokemon:0763",
    "label": "ニャスパー"
  },
  {
    "id": "pokemon:0764",
    "label": "ニャオニクス"
  },
  {
    "id": "pokemon:0765",
    "label": "ニャオニクス♂"
  },
  {
    "id": "pokemon:0766",
    "label": "ニャオニクス♀"
  },
  {
    "id": "pokemon:0767",
    "label": "メガニャオニクス"
  },
  {
    "id": "pokemon:0768",
    "label": "メガニャオニクス♂"
  },
  {
    "id": "pokemon:0769",
    "label": "メガニャオニクス♀"
  },
  {
    "id": "pokemon:0770",
    "label": "ヒトツキ"
  },
  {
    "id": "pokemon:0771",
    "label": "ニダンギル"
  },
  {
    "id": "pokemon:0772",
    "label": "ギルガルド"
  },
  {
    "id": "pokemon:0773",
    "label": "シュシュプ"
  },
  {
    "id": "pokemon:0774",
    "label": "フレフワン"
  },
  {
    "id": "pokemon:0775",
    "label": "ペロッパフ"
  },
  {
    "id": "pokemon:0776",
    "label": "ペロリーム"
  },
  {
    "id": "pokemon:0777",
    "label": "マーイーカ"
  },
  {
    "id": "pokemon:0778",
    "label": "カラマネロ"
  },
  {
    "id": "pokemon:0779",
    "label": "メガカラマネロ"
  },
  {
    "id": "pokemon:0780",
    "label": "カメテテ"
  },
  {
    "id": "pokemon:0781",
    "label": "ガメノデス"
  },
  {
    "id": "pokemon:0782",
    "label": "メガガメノデス"
  },
  {
    "id": "pokemon:0783",
    "label": "クズモー"
  },
  {
    "id": "pokemon:0784",
    "label": "ドラミドロ"
  },
  {
    "id": "pokemon:0785",
    "label": "メガドラミドロ"
  },
  {
    "id": "pokemon:0786",
    "label": "ウデッポウ"
  },
  {
    "id": "pokemon:0787",
    "label": "ブロスター"
  },
  {
    "id": "pokemon:0788",
    "label": "エリキテル"
  },
  {
    "id": "pokemon:0789",
    "label": "エレザード"
  },
  {
    "id": "pokemon:0790",
    "label": "チゴラス"
  },
  {
    "id": "pokemon:0791",
    "label": "ガチゴラス"
  },
  {
    "id": "pokemon:0792",
    "label": "アマルス"
  },
  {
    "id": "pokemon:0793",
    "label": "アマルルガ"
  },
  {
    "id": "pokemon:0794",
    "label": "ニンフィア"
  },
  {
    "id": "pokemon:0795",
    "label": "ルチャブル"
  },
  {
    "id": "pokemon:0796",
    "label": "メガルチャブル"
  },
  {
    "id": "pokemon:0797",
    "label": "デデンネ"
  },
  {
    "id": "pokemon:0798",
    "label": "メレシー"
  },
  {
    "id": "pokemon:0799",
    "label": "ヌメラ"
  },
  {
    "id": "pokemon:0800",
    "label": "ヌメイル"
  },
  {
    "id": "pokemon:0801",
    "label": "ヌメルゴン"
  },
  {
    "id": "pokemon:0802",
    "label": "クレッフィ"
  },
  {
    "id": "pokemon:0803",
    "label": "ボクレー"
  },
  {
    "id": "pokemon:0804",
    "label": "オーロット"
  },
  {
    "id": "pokemon:0805",
    "label": "バケッチャ"
  },
  {
    "id": "pokemon:0806",
    "label": "パンプジン"
  },
  {
    "id": "pokemon:0807",
    "label": "カチコール"
  },
  {
    "id": "pokemon:0808",
    "label": "クレベース"
  },
  {
    "id": "pokemon:0809",
    "label": "オンバット"
  },
  {
    "id": "pokemon:0810",
    "label": "オンバーン"
  },
  {
    "id": "pokemon:0811",
    "label": "ゼルネアス"
  },
  {
    "id": "pokemon:0812",
    "label": "イベルタル"
  },
  {
    "id": "pokemon:0813",
    "label": "ジガルデ"
  },
  {
    "id": "pokemon:0814",
    "label": "メガジガルデ"
  },
  {
    "id": "pokemon:0815",
    "label": "ディアンシー"
  },
  {
    "id": "pokemon:0816",
    "label": "メガディアンシー"
  },
  {
    "id": "pokemon:0817",
    "label": "フーパ"
  },
  {
    "id": "pokemon:0818",
    "label": "ボルケニオン"
  },
  {
    "id": "pokemon:0819",
    "label": "モクロー"
  },
  {
    "id": "pokemon:0820",
    "label": "フクスロー"
  },
  {
    "id": "pokemon:0821",
    "label": "ジュナイパー"
  },
  {
    "id": "pokemon:0822",
    "label": "ニャビー"
  },
  {
    "id": "pokemon:0823",
    "label": "ニャヒート"
  },
  {
    "id": "pokemon:0824",
    "label": "ガオガエン"
  },
  {
    "id": "pokemon:0825",
    "label": "アシマリ"
  },
  {
    "id": "pokemon:0826",
    "label": "オシャマリ"
  },
  {
    "id": "pokemon:0827",
    "label": "アシレーヌ"
  },
  {
    "id": "pokemon:0828",
    "label": "ツツケラ"
  },
  {
    "id": "pokemon:0829",
    "label": "ケララッパ"
  },
  {
    "id": "pokemon:0830",
    "label": "ドデカバシ"
  },
  {
    "id": "pokemon:0831",
    "label": "ヤングース"
  },
  {
    "id": "pokemon:0832",
    "label": "デカグース"
  },
  {
    "id": "pokemon:0833",
    "label": "アゴジムシ"
  },
  {
    "id": "pokemon:0834",
    "label": "デンヂムシ"
  },
  {
    "id": "pokemon:0835",
    "label": "クワガノン"
  },
  {
    "id": "pokemon:0836",
    "label": "マケンカニ"
  },
  {
    "id": "pokemon:0837",
    "label": "ケケンカニ"
  },
  {
    "id": "pokemon:0838",
    "label": "メガケケンカニ"
  },
  {
    "id": "pokemon:0839",
    "label": "オドリドリ"
  },
  {
    "id": "pokemon:0840",
    "label": "アブリー"
  },
  {
    "id": "pokemon:0841",
    "label": "アブリボン"
  },
  {
    "id": "pokemon:0842",
    "label": "イワンコ"
  },
  {
    "id": "pokemon:0843",
    "label": "ルガルガン"
  },
  {
    "id": "pokemon:0844",
    "label": "ヨワシ"
  },
  {
    "id": "pokemon:0845",
    "label": "ヒドイデ"
  },
  {
    "id": "pokemon:0846",
    "label": "ドヒドイデ"
  },
  {
    "id": "pokemon:0847",
    "label": "ドロバンコ"
  },
  {
    "id": "pokemon:0848",
    "label": "バンバドロ"
  },
  {
    "id": "pokemon:0849",
    "label": "シズクモ"
  },
  {
    "id": "pokemon:0850",
    "label": "オニシズクモ"
  },
  {
    "id": "pokemon:0851",
    "label": "カリキリ"
  },
  {
    "id": "pokemon:0852",
    "label": "ラランテス"
  },
  {
    "id": "pokemon:0853",
    "label": "ネマシュ"
  },
  {
    "id": "pokemon:0854",
    "label": "マシェード"
  },
  {
    "id": "pokemon:0855",
    "label": "ヤトウモリ"
  },
  {
    "id": "pokemon:0856",
    "label": "エンニュート"
  },
  {
    "id": "pokemon:0857",
    "label": "ヌイコグマ"
  },
  {
    "id": "pokemon:0858",
    "label": "キテルグマ"
  },
  {
    "id": "pokemon:0859",
    "label": "アマカジ"
  },
  {
    "id": "pokemon:0860",
    "label": "アママイコ"
  },
  {
    "id": "pokemon:0861",
    "label": "アマージョ"
  },
  {
    "id": "pokemon:0862",
    "label": "キュワワー"
  },
  {
    "id": "pokemon:0863",
    "label": "ヤレユータン"
  },
  {
    "id": "pokemon:0864",
    "label": "ナゲツケサル"
  },
  {
    "id": "pokemon:0865",
    "label": "コソクムシ"
  },
  {
    "id": "pokemon:0866",
    "label": "グソクムシャ"
  },
  {
    "id": "pokemon:0867",
    "label": "メガグソクムシャ"
  },
  {
    "id": "pokemon:0868",
    "label": "スナバァ"
  },
  {
    "id": "pokemon:0869",
    "label": "シロデスナ"
  },
  {
    "id": "pokemon:0870",
    "label": "ナマコブシ"
  },
  {
    "id": "pokemon:0871",
    "label": "タイプ:ヌル"
  },
  {
    "id": "pokemon:0872",
    "label": "シルヴァディ"
  },
  {
    "id": "pokemon:0873",
    "label": "メテノ"
  },
  {
    "id": "pokemon:0874",
    "label": "ネッコアラ"
  },
  {
    "id": "pokemon:0875",
    "label": "バクガメス"
  },
  {
    "id": "pokemon:0876",
    "label": "トゲデマル"
  },
  {
    "id": "pokemon:0877",
    "label": "ミミッキュ"
  },
  {
    "id": "pokemon:0878",
    "label": "ハギギシリ"
  },
  {
    "id": "pokemon:0879",
    "label": "ジジーロン"
  },
  {
    "id": "pokemon:0880",
    "label": "メガジジーロン"
  },
  {
    "id": "pokemon:0881",
    "label": "ダダリン"
  },
  {
    "id": "pokemon:0882",
    "label": "ジャラコ"
  },
  {
    "id": "pokemon:0883",
    "label": "ジャランゴ"
  },
  {
    "id": "pokemon:0884",
    "label": "ジャラランガ"
  },
  {
    "id": "pokemon:0885",
    "label": "カプ・コケコ"
  },
  {
    "id": "pokemon:0886",
    "label": "カプ・テテフ"
  },
  {
    "id": "pokemon:0887",
    "label": "カプ・ブルル"
  },
  {
    "id": "pokemon:0888",
    "label": "カプ・レヒレ"
  },
  {
    "id": "pokemon:0889",
    "label": "コスモッグ"
  },
  {
    "id": "pokemon:0890",
    "label": "コスモウム"
  },
  {
    "id": "pokemon:0891",
    "label": "ソルガレオ"
  },
  {
    "id": "pokemon:0892",
    "label": "ルナアーラ"
  },
  {
    "id": "pokemon:0893",
    "label": "ウツロイド"
  },
  {
    "id": "pokemon:0894",
    "label": "マッシブーン"
  },
  {
    "id": "pokemon:0895",
    "label": "フェローチェ"
  },
  {
    "id": "pokemon:0896",
    "label": "デンジュモク"
  },
  {
    "id": "pokemon:0897",
    "label": "テッカグヤ"
  },
  {
    "id": "pokemon:0898",
    "label": "カミツルギ"
  },
  {
    "id": "pokemon:0899",
    "label": "アクジキング"
  },
  {
    "id": "pokemon:0900",
    "label": "ネクロズマ"
  },
  {
    "id": "pokemon:0901",
    "label": "ウルトラネクロズマ"
  },
  {
    "id": "pokemon:0902",
    "label": "マギアナ"
  },
  {
    "id": "pokemon:0903",
    "label": "メガマギアナ"
  },
  {
    "id": "pokemon:0904",
    "label": "マーシャドー"
  },
  {
    "id": "pokemon:0905",
    "label": "ベベノム"
  },
  {
    "id": "pokemon:0906",
    "label": "アーゴヨン"
  },
  {
    "id": "pokemon:0907",
    "label": "ツンデツンデ"
  },
  {
    "id": "pokemon:0908",
    "label": "ズガドーン"
  },
  {
    "id": "pokemon:0909",
    "label": "ゼラオラ"
  },
  {
    "id": "pokemon:0910",
    "label": "メガゼラオラ"
  },
  {
    "id": "pokemon:0911",
    "label": "メルタン"
  },
  {
    "id": "pokemon:0912",
    "label": "メルメタル"
  },
  {
    "id": "pokemon:0913",
    "label": "サルノリ"
  },
  {
    "id": "pokemon:0914",
    "label": "バチンキー"
  },
  {
    "id": "pokemon:0915",
    "label": "ゴリランダー"
  },
  {
    "id": "pokemon:0916",
    "label": "ヒバニー"
  },
  {
    "id": "pokemon:0917",
    "label": "ラビフット"
  },
  {
    "id": "pokemon:0918",
    "label": "エースバーン"
  },
  {
    "id": "pokemon:0919",
    "label": "メッソン"
  },
  {
    "id": "pokemon:0920",
    "label": "ジメレオン"
  },
  {
    "id": "pokemon:0921",
    "label": "インテレオン"
  },
  {
    "id": "pokemon:0922",
    "label": "ホシガリス"
  },
  {
    "id": "pokemon:0923",
    "label": "ヨクバリス"
  },
  {
    "id": "pokemon:0924",
    "label": "ココガラ"
  },
  {
    "id": "pokemon:0925",
    "label": "アオガラス"
  },
  {
    "id": "pokemon:0926",
    "label": "アーマーガア"
  },
  {
    "id": "pokemon:0927",
    "label": "サッチムシ"
  },
  {
    "id": "pokemon:0928",
    "label": "レドームシ"
  },
  {
    "id": "pokemon:0929",
    "label": "イオルブ"
  },
  {
    "id": "pokemon:0930",
    "label": "クスネ"
  },
  {
    "id": "pokemon:0931",
    "label": "フォクスライ"
  },
  {
    "id": "pokemon:0932",
    "label": "ヒメンカ"
  },
  {
    "id": "pokemon:0933",
    "label": "ワタシラガ"
  },
  {
    "id": "pokemon:0934",
    "label": "ウールー"
  },
  {
    "id": "pokemon:0935",
    "label": "バイウールー"
  },
  {
    "id": "pokemon:0936",
    "label": "カムカメ"
  },
  {
    "id": "pokemon:0937",
    "label": "カジリガメ"
  },
  {
    "id": "pokemon:0938",
    "label": "ワンパチ"
  },
  {
    "id": "pokemon:0939",
    "label": "パルスワン"
  },
  {
    "id": "pokemon:0940",
    "label": "タンドン"
  },
  {
    "id": "pokemon:0941",
    "label": "トロッゴン"
  },
  {
    "id": "pokemon:0942",
    "label": "セキタンザン"
  },
  {
    "id": "pokemon:0943",
    "label": "カジッチュ"
  },
  {
    "id": "pokemon:0944",
    "label": "アップリュー"
  },
  {
    "id": "pokemon:0945",
    "label": "タルップル"
  },
  {
    "id": "pokemon:0946",
    "label": "スナヘビ"
  },
  {
    "id": "pokemon:0947",
    "label": "サダイジャ"
  },
  {
    "id": "pokemon:0948",
    "label": "ウッウ"
  },
  {
    "id": "pokemon:0949",
    "label": "サシカマス"
  },
  {
    "id": "pokemon:0950",
    "label": "カマスジョー"
  },
  {
    "id": "pokemon:0951",
    "label": "エレズン"
  },
  {
    "id": "pokemon:0952",
    "label": "ストリンダー"
  },
  {
    "id": "pokemon:0953",
    "label": "ヤクデ"
  },
  {
    "id": "pokemon:0954",
    "label": "マルヤクデ"
  },
  {
    "id": "pokemon:0955",
    "label": "タタッコ"
  },
  {
    "id": "pokemon:0956",
    "label": "オトスパス"
  },
  {
    "id": "pokemon:0957",
    "label": "ヤバチャ"
  },
  {
    "id": "pokemon:0958",
    "label": "ポットデス"
  },
  {
    "id": "pokemon:0959",
    "label": "ミブリム"
  },
  {
    "id": "pokemon:0960",
    "label": "テブリム"
  },
  {
    "id": "pokemon:0961",
    "label": "ブリムオン"
  },
  {
    "id": "pokemon:0962",
    "label": "ベロバー"
  },
  {
    "id": "pokemon:0963",
    "label": "ギモー"
  },
  {
    "id": "pokemon:0964",
    "label": "オーロンゲ"
  },
  {
    "id": "pokemon:0965",
    "label": "タチフサグマ"
  },
  {
    "id": "pokemon:0966",
    "label": "ニャイキング"
  },
  {
    "id": "pokemon:0967",
    "label": "サニゴーン"
  },
  {
    "id": "pokemon:0968",
    "label": "ネギガナイト"
  },
  {
    "id": "pokemon:0969",
    "label": "バリコオル"
  },
  {
    "id": "pokemon:0970",
    "label": "デスバーン"
  },
  {
    "id": "pokemon:0971",
    "label": "マホミル"
  },
  {
    "id": "pokemon:0972",
    "label": "マホイップ"
  },
  {
    "id": "pokemon:0973",
    "label": "タイレーツ"
  },
  {
    "id": "pokemon:0974",
    "label": "メガタイレーツ"
  },
  {
    "id": "pokemon:0975",
    "label": "バチンウニ"
  },
  {
    "id": "pokemon:0976",
    "label": "ユキハミ"
  },
  {
    "id": "pokemon:0977",
    "label": "モスノウ"
  },
  {
    "id": "pokemon:0978",
    "label": "イシヘンジン"
  },
  {
    "id": "pokemon:0979",
    "label": "コオリッポ"
  },
  {
    "id": "pokemon:0980",
    "label": "イエッサン"
  },
  {
    "id": "pokemon:0981",
    "label": "イエッサン♂"
  },
  {
    "id": "pokemon:0982",
    "label": "イエッサン♀"
  },
  {
    "id": "pokemon:0983",
    "label": "モルペコ"
  },
  {
    "id": "pokemon:0984",
    "label": "ゾウドウ"
  },
  {
    "id": "pokemon:0985",
    "label": "ダイオウドウ"
  },
  {
    "id": "pokemon:0986",
    "label": "パッチラゴン"
  },
  {
    "id": "pokemon:0987",
    "label": "パッチルドン"
  },
  {
    "id": "pokemon:0988",
    "label": "ウオノラゴン"
  },
  {
    "id": "pokemon:0989",
    "label": "ウオチルドン"
  },
  {
    "id": "pokemon:0990",
    "label": "ジュラルドン"
  },
  {
    "id": "pokemon:0991",
    "label": "ドラメシヤ"
  },
  {
    "id": "pokemon:0992",
    "label": "ドロンチ"
  },
  {
    "id": "pokemon:0993",
    "label": "ドラパルト"
  },
  {
    "id": "pokemon:0994",
    "label": "ザシアン"
  },
  {
    "id": "pokemon:0995",
    "label": "ザマゼンタ"
  },
  {
    "id": "pokemon:0996",
    "label": "ムゲンダイナ"
  },
  {
    "id": "pokemon:0997",
    "label": "ダクマ"
  },
  {
    "id": "pokemon:0998",
    "label": "ウーラオス"
  },
  {
    "id": "pokemon:0999",
    "label": "ザルード"
  },
  {
    "id": "pokemon:1000",
    "label": "レジエレキ"
  },
  {
    "id": "pokemon:1001",
    "label": "レジドラゴ"
  },
  {
    "id": "pokemon:1002",
    "label": "ブリザポス"
  },
  {
    "id": "pokemon:1003",
    "label": "レイスポス"
  },
  {
    "id": "pokemon:1004",
    "label": "バドレックス"
  },
  {
    "id": "pokemon:1005",
    "label": "アヤシシ"
  },
  {
    "id": "pokemon:1006",
    "label": "バサギリ"
  },
  {
    "id": "pokemon:1007",
    "label": "ガチグマ"
  },
  {
    "id": "pokemon:1008",
    "label": "イダイトウ"
  },
  {
    "id": "pokemon:1009",
    "label": "イダイトウ♂"
  },
  {
    "id": "pokemon:1010",
    "label": "イダイトウ♀"
  },
  {
    "id": "pokemon:1011",
    "label": "オオニューラ"
  },
  {
    "id": "pokemon:1012",
    "label": "ハリーマン"
  },
  {
    "id": "pokemon:1013",
    "label": "ラブトロス"
  },
  {
    "id": "pokemon:1014",
    "label": "ニャオハ"
  },
  {
    "id": "pokemon:1015",
    "label": "ニャローテ"
  },
  {
    "id": "pokemon:1016",
    "label": "マスカーニャ"
  },
  {
    "id": "pokemon:1017",
    "label": "ホゲータ"
  },
  {
    "id": "pokemon:1018",
    "label": "アチゲータ"
  },
  {
    "id": "pokemon:1019",
    "label": "ラウドボーン"
  },
  {
    "id": "pokemon:1020",
    "label": "クワッス"
  },
  {
    "id": "pokemon:1021",
    "label": "ウェルカモ"
  },
  {
    "id": "pokemon:1022",
    "label": "ウェーニバル"
  },
  {
    "id": "pokemon:1023",
    "label": "グルトン"
  },
  {
    "id": "pokemon:1024",
    "label": "パフュートン"
  },
  {
    "id": "pokemon:1025",
    "label": "パフュートン♂"
  },
  {
    "id": "pokemon:1026",
    "label": "パフュートン♀"
  },
  {
    "id": "pokemon:1027",
    "label": "タマンチュラ"
  },
  {
    "id": "pokemon:1028",
    "label": "ワナイダー"
  },
  {
    "id": "pokemon:1029",
    "label": "マメバッタ"
  },
  {
    "id": "pokemon:1030",
    "label": "エクスレッグ"
  },
  {
    "id": "pokemon:1031",
    "label": "パモ"
  },
  {
    "id": "pokemon:1032",
    "label": "パモット"
  },
  {
    "id": "pokemon:1033",
    "label": "パーモット"
  },
  {
    "id": "pokemon:1034",
    "label": "ワッカネズミ"
  },
  {
    "id": "pokemon:1035",
    "label": "イッカネズミ"
  },
  {
    "id": "pokemon:1036",
    "label": "パピモッチ"
  },
  {
    "id": "pokemon:1037",
    "label": "バウッツェル"
  },
  {
    "id": "pokemon:1038",
    "label": "ミニーブ"
  },
  {
    "id": "pokemon:1039",
    "label": "オリーニョ"
  },
  {
    "id": "pokemon:1040",
    "label": "オリーヴァ"
  },
  {
    "id": "pokemon:1041",
    "label": "イキリンコ"
  },
  {
    "id": "pokemon:1042",
    "label": "コジオ"
  },
  {
    "id": "pokemon:1043",
    "label": "ジオヅム"
  },
  {
    "id": "pokemon:1044",
    "label": "キョジオーン"
  },
  {
    "id": "pokemon:1045",
    "label": "カルボウ"
  },
  {
    "id": "pokemon:1046",
    "label": "グレンアルマ"
  },
  {
    "id": "pokemon:1047",
    "label": "ソウブレイズ"
  },
  {
    "id": "pokemon:1048",
    "label": "ズピカ"
  },
  {
    "id": "pokemon:1049",
    "label": "ハラバリー"
  },
  {
    "id": "pokemon:1050",
    "label": "カイデン"
  },
  {
    "id": "pokemon:1051",
    "label": "タイカイデン"
  },
  {
    "id": "pokemon:1052",
    "label": "オラチフ"
  },
  {
    "id": "pokemon:1053",
    "label": "マフィティフ"
  },
  {
    "id": "pokemon:1054",
    "label": "シルシュルー"
  },
  {
    "id": "pokemon:1055",
    "label": "タギングル"
  },
  {
    "id": "pokemon:1056",
    "label": "アノクサ"
  },
  {
    "id": "pokemon:1057",
    "label": "アノホラグサ"
  },
  {
    "id": "pokemon:1058",
    "label": "ノノクラゲ"
  },
  {
    "id": "pokemon:1059",
    "label": "リククラゲ"
  },
  {
    "id": "pokemon:1060",
    "label": "ガケガニ"
  },
  {
    "id": "pokemon:1061",
    "label": "カプサイジ"
  },
  {
    "id": "pokemon:1062",
    "label": "スコヴィラン"
  },
  {
    "id": "pokemon:1063",
    "label": "メガスコヴィラン"
  },
  {
    "id": "pokemon:1064",
    "label": "シガロコ"
  },
  {
    "id": "pokemon:1065",
    "label": "ベラカス"
  },
  {
    "id": "pokemon:1066",
    "label": "ヒラヒナ"
  },
  {
    "id": "pokemon:1067",
    "label": "クエスパトラ"
  },
  {
    "id": "pokemon:1068",
    "label": "カヌチャン"
  },
  {
    "id": "pokemon:1069",
    "label": "ナカヌチャン"
  },
  {
    "id": "pokemon:1070",
    "label": "デカヌチャン"
  },
  {
    "id": "pokemon:1071",
    "label": "ウミディグダ"
  },
  {
    "id": "pokemon:1072",
    "label": "ウミトリオ"
  },
  {
    "id": "pokemon:1073",
    "label": "オトシドリ"
  },
  {
    "id": "pokemon:1074",
    "label": "ナミイルカ"
  },
  {
    "id": "pokemon:1075",
    "label": "イルカマン"
  },
  {
    "id": "pokemon:1076",
    "label": "ブロロン"
  },
  {
    "id": "pokemon:1077",
    "label": "ブロロローム"
  },
  {
    "id": "pokemon:1078",
    "label": "モトトカゲ"
  },
  {
    "id": "pokemon:1079",
    "label": "ミミズズ"
  },
  {
    "id": "pokemon:1080",
    "label": "キラーメ"
  },
  {
    "id": "pokemon:1081",
    "label": "キラフロル"
  },
  {
    "id": "pokemon:1082",
    "label": "メガキラフロル"
  },
  {
    "id": "pokemon:1083",
    "label": "ボチ"
  },
  {
    "id": "pokemon:1084",
    "label": "ハカドッグ"
  },
  {
    "id": "pokemon:1085",
    "label": "カラミンゴ"
  },
  {
    "id": "pokemon:1086",
    "label": "アルクジラ"
  },
  {
    "id": "pokemon:1087",
    "label": "ハルクジラ"
  },
  {
    "id": "pokemon:1088",
    "label": "ミガルーサ"
  },
  {
    "id": "pokemon:1089",
    "label": "ヘイラッシャ"
  },
  {
    "id": "pokemon:1090",
    "label": "シャリタツ"
  },
  {
    "id": "pokemon:1091",
    "label": "メガシャリタツ"
  },
  {
    "id": "pokemon:1092",
    "label": "コノヨザル"
  },
  {
    "id": "pokemon:1093",
    "label": "ドオー"
  },
  {
    "id": "pokemon:1094",
    "label": "リキキリン"
  },
  {
    "id": "pokemon:1095",
    "label": "ノココッチ"
  },
  {
    "id": "pokemon:1096",
    "label": "ドドゲザン"
  },
  {
    "id": "pokemon:1097",
    "label": "イダイナキバ"
  },
  {
    "id": "pokemon:1098",
    "label": "サケブシッポ"
  },
  {
    "id": "pokemon:1099",
    "label": "アラブルタケ"
  },
  {
    "id": "pokemon:1100",
    "label": "ハバタクカミ"
  },
  {
    "id": "pokemon:1101",
    "label": "チヲハウハネ"
  },
  {
    "id": "pokemon:1102",
    "label": "スナノケガワ"
  },
  {
    "id": "pokemon:1103",
    "label": "テツノワダチ"
  },
  {
    "id": "pokemon:1104",
    "label": "テツノツツミ"
  },
  {
    "id": "pokemon:1105",
    "label": "テツノカイナ"
  },
  {
    "id": "pokemon:1106",
    "label": "テツノコウベ"
  },
  {
    "id": "pokemon:1107",
    "label": "テツノドクガ"
  },
  {
    "id": "pokemon:1108",
    "label": "テツノイバラ"
  },
  {
    "id": "pokemon:1109",
    "label": "セビエ"
  },
  {
    "id": "pokemon:1110",
    "label": "セゴール"
  },
  {
    "id": "pokemon:1111",
    "label": "セグレイブ"
  },
  {
    "id": "pokemon:1112",
    "label": "メガセグレイブ"
  },
  {
    "id": "pokemon:1113",
    "label": "コレクレー"
  },
  {
    "id": "pokemon:1114",
    "label": "サーフゴー"
  },
  {
    "id": "pokemon:1115",
    "label": "チオンジェン"
  },
  {
    "id": "pokemon:1116",
    "label": "パオジアン"
  },
  {
    "id": "pokemon:1117",
    "label": "ディンルー"
  },
  {
    "id": "pokemon:1118",
    "label": "イーユイ"
  },
  {
    "id": "pokemon:1119",
    "label": "トドロクツキ"
  },
  {
    "id": "pokemon:1120",
    "label": "テツノブジン"
  },
  {
    "id": "pokemon:1121",
    "label": "コライドン"
  },
  {
    "id": "pokemon:1122",
    "label": "ミライドン"
  },
  {
    "id": "pokemon:1123",
    "label": "ウネルミナモ"
  },
  {
    "id": "pokemon:1124",
    "label": "テツノイサハ"
  },
  {
    "id": "pokemon:1125",
    "label": "カミッチュ"
  },
  {
    "id": "pokemon:1126",
    "label": "チャデス"
  },
  {
    "id": "pokemon:1127",
    "label": "ヤバソチャ"
  },
  {
    "id": "pokemon:1128",
    "label": "イイネイヌ"
  },
  {
    "id": "pokemon:1129",
    "label": "マシマシラ"
  },
  {
    "id": "pokemon:1130",
    "label": "キチキギス"
  },
  {
    "id": "pokemon:1131",
    "label": "オーガポン"
  },
  {
    "id": "pokemon:1132",
    "label": "ブリジュラス"
  },
  {
    "id": "pokemon:1133",
    "label": "カミツオロチ"
  },
  {
    "id": "pokemon:1134",
    "label": "ウガツホムラ"
  },
  {
    "id": "pokemon:1135",
    "label": "タケルライコ"
  },
  {
    "id": "pokemon:1136",
    "label": "テツノイワオ"
  },
  {
    "id": "pokemon:1137",
    "label": "テツノカシラ"
  },
  {
    "id": "pokemon:1138",
    "label": "テラパゴス"
  },
  {
    "id": "pokemon:1139",
    "label": "モモワロウ"
  }
];

export const MOVE_NAME_DICTIONARY: readonly DictionaryEntry[] = [
  {
    "id": "move:0001",
    "label": "3ぼんのや"
  },
  {
    "id": "move:0002",
    "label": "アーマーキャノン"
  },
  {
    "id": "move:0003",
    "label": "アームハンマー"
  },
  {
    "id": "move:0004",
    "label": "アイアンテール"
  },
  {
    "id": "move:0005",
    "label": "アイアンヘッド"
  },
  {
    "id": "move:0006",
    "label": "アイアンローラー"
  },
  {
    "id": "move:0007",
    "label": "アイススピナー"
  },
  {
    "id": "move:0008",
    "label": "アイスハンマー"
  },
  {
    "id": "move:0009",
    "label": "アクアカッター"
  },
  {
    "id": "move:0010",
    "label": "アクアジェット"
  },
  {
    "id": "move:0011",
    "label": "アクアステップ"
  },
  {
    "id": "move:0012",
    "label": "アクアテール"
  },
  {
    "id": "move:0013",
    "label": "アクアブレイク"
  },
  {
    "id": "move:0014",
    "label": "アクアリング"
  },
  {
    "id": "move:0015",
    "label": "アクセルロック"
  },
  {
    "id": "move:0016",
    "label": "あくのはどう"
  },
  {
    "id": "move:0017",
    "label": "あくび"
  },
  {
    "id": "move:0018",
    "label": "アクロバット"
  },
  {
    "id": "move:0019",
    "label": "あさのひざし"
  },
  {
    "id": "move:0020",
    "label": "アシストパワー"
  },
  {
    "id": "move:0021",
    "label": "アシッドボム"
  },
  {
    "id": "move:0022",
    "label": "あなをほる"
  },
  {
    "id": "move:0023",
    "label": "あばれる"
  },
  {
    "id": "move:0024",
    "label": "あまいかおり"
  },
  {
    "id": "move:0025",
    "label": "あまえる"
  },
  {
    "id": "move:0026",
    "label": "あまごい"
  },
  {
    "id": "move:0027",
    "label": "あやしいひかり"
  },
  {
    "id": "move:0028",
    "label": "アロマミスト"
  },
  {
    "id": "move:0029",
    "label": "アンコール"
  },
  {
    "id": "move:0030",
    "label": "いえき"
  },
  {
    "id": "move:0031",
    "label": "イカサマ"
  },
  {
    "id": "move:0032",
    "label": "いかりのこな"
  },
  {
    "id": "move:0033",
    "label": "いかりのまえば"
  },
  {
    "id": "move:0034",
    "label": "いたみわけ"
  },
  {
    "id": "move:0035",
    "label": "いちゃもん"
  },
  {
    "id": "move:0036",
    "label": "いとをはく"
  },
  {
    "id": "move:0037",
    "label": "いのちがけ"
  },
  {
    "id": "move:0038",
    "label": "いのちのしずく"
  },
  {
    "id": "move:0039",
    "label": "いばる"
  },
  {
    "id": "move:0040",
    "label": "いびき"
  },
  {
    "id": "move:0041",
    "label": "いやしのすず"
  },
  {
    "id": "move:0042",
    "label": "いやしのねがい"
  },
  {
    "id": "move:0043",
    "label": "いやしのはどう"
  },
  {
    "id": "move:0044",
    "label": "いやなおと"
  },
  {
    "id": "move:0045",
    "label": "いわなだれ"
  },
  {
    "id": "move:0046",
    "label": "インファイト"
  },
  {
    "id": "move:0047",
    "label": "ウェーブタックル"
  },
  {
    "id": "move:0048",
    "label": "ウェザーボール"
  },
  {
    "id": "move:0049",
    "label": "うずしお"
  },
  {
    "id": "move:0050",
    "label": "うそなき"
  },
  {
    "id": "move:0051",
    "label": "うたう"
  },
  {
    "id": "move:0052",
    "label": "うたかたのアリア"
  },
  {
    "id": "move:0053",
    "label": "うちおとす"
  },
  {
    "id": "move:0054",
    "label": "ウッドハンマー"
  },
  {
    "id": "move:0055",
    "label": "ウッドホーン"
  },
  {
    "id": "move:0056",
    "label": "うっぷんばらし"
  },
  {
    "id": "move:0057",
    "label": "うらみ"
  },
  {
    "id": "move:0058",
    "label": "うらみつらみ"
  },
  {
    "id": "move:0059",
    "label": "エアカッター"
  },
  {
    "id": "move:0060",
    "label": "エアスラッシュ"
  },
  {
    "id": "move:0061",
    "label": "エナジーボール"
  },
  {
    "id": "move:0062",
    "label": "エレキネット"
  },
  {
    "id": "move:0063",
    "label": "エレキフィールド"
  },
  {
    "id": "move:0064",
    "label": "エレキボール"
  },
  {
    "id": "move:0065",
    "label": "エレクトロビーム"
  },
  {
    "id": "move:0066",
    "label": "オーバーヒート"
  },
  {
    "id": "move:0067",
    "label": "オーラぐるま"
  },
  {
    "id": "move:0068",
    "label": "オーロラベール"
  },
  {
    "id": "move:0069",
    "label": "おいかぜ"
  },
  {
    "id": "move:0070",
    "label": "おかたづけ"
  },
  {
    "id": "move:0071",
    "label": "おきみやげ"
  },
  {
    "id": "move:0072",
    "label": "おさきにどうぞ"
  },
  {
    "id": "move:0073",
    "label": "おたけび"
  },
  {
    "id": "move:0074",
    "label": "おだてる"
  },
  {
    "id": "move:0075",
    "label": "おちゃかい"
  },
  {
    "id": "move:0076",
    "label": "おにび"
  },
  {
    "id": "move:0077",
    "label": "おはかまいり"
  },
  {
    "id": "move:0078",
    "label": "かいでんぱ"
  },
  {
    "id": "move:0079",
    "label": "カウンター"
  },
  {
    "id": "move:0080",
    "label": "かえんほうしゃ"
  },
  {
    "id": "move:0081",
    "label": "かかとおとし"
  },
  {
    "id": "move:0082",
    "label": "かげうち"
  },
  {
    "id": "move:0083",
    "label": "かげぬい"
  },
  {
    "id": "move:0084",
    "label": "かげぶんしん"
  },
  {
    "id": "move:0085",
    "label": "かなしばり"
  },
  {
    "id": "move:0086",
    "label": "かふんだんご"
  },
  {
    "id": "move:0087",
    "label": "かみくだく"
  },
  {
    "id": "move:0088",
    "label": "かみつく"
  },
  {
    "id": "move:0089",
    "label": "かみなり"
  },
  {
    "id": "move:0090",
    "label": "かみなりのキバ"
  },
  {
    "id": "move:0091",
    "label": "かみなりパンチ"
  },
  {
    "id": "move:0092",
    "label": "からげんき"
  },
  {
    "id": "move:0093",
    "label": "からをやぶる"
  },
  {
    "id": "move:0094",
    "label": "かわらわり"
  },
  {
    "id": "move:0095",
    "label": "ガードシェア"
  },
  {
    "id": "move:0096",
    "label": "ガードスワップ"
  },
  {
    "id": "move:0097",
    "label": "がむしゃら"
  },
  {
    "id": "move:0098",
    "label": "がんせきアックス"
  },
  {
    "id": "move:0099",
    "label": "がんせきふうじ"
  },
  {
    "id": "move:0100",
    "label": "がんせきほう"
  },
  {
    "id": "move:0101",
    "label": "きあいだま"
  },
  {
    "id": "move:0102",
    "label": "きあいだめ"
  },
  {
    "id": "move:0103",
    "label": "きあいパンチ"
  },
  {
    "id": "move:0104",
    "label": "きしかいせい"
  },
  {
    "id": "move:0105",
    "label": "きまぐレーザー"
  },
  {
    "id": "move:0106",
    "label": "きゅうけつ"
  },
  {
    "id": "move:0107",
    "label": "キラースピン"
  },
  {
    "id": "move:0108",
    "label": "きりばらい"
  },
  {
    "id": "move:0109",
    "label": "キングシールド"
  },
  {
    "id": "move:0110",
    "label": "きんぞくおん"
  },
  {
    "id": "move:0111",
    "label": "ギガインパクト"
  },
  {
    "id": "move:0112",
    "label": "ギガドレイン"
  },
  {
    "id": "move:0113",
    "label": "クイックターン"
  },
  {
    "id": "move:0114",
    "label": "くさむすび"
  },
  {
    "id": "move:0115",
    "label": "くさわけ"
  },
  {
    "id": "move:0116",
    "label": "くすぐる"
  },
  {
    "id": "move:0117",
    "label": "くちばしキャノン"
  },
  {
    "id": "move:0118",
    "label": "クラブハンマー"
  },
  {
    "id": "move:0119",
    "label": "クリアスモッグ"
  },
  {
    "id": "move:0120",
    "label": "くろいきり"
  },
  {
    "id": "move:0121",
    "label": "くろいまなざし"
  },
  {
    "id": "move:0122",
    "label": "クロスチョップ"
  },
  {
    "id": "move:0123",
    "label": "クロスポイズン"
  },
  {
    "id": "move:0124",
    "label": "グラススライダー"
  },
  {
    "id": "move:0125",
    "label": "グラスフィールド"
  },
  {
    "id": "move:0126",
    "label": "けたぐり"
  },
  {
    "id": "move:0127",
    "label": "げきりん"
  },
  {
    "id": "move:0128",
    "label": "ゲップ"
  },
  {
    "id": "move:0129",
    "label": "げんしのちから"
  },
  {
    "id": "move:0130",
    "label": "コーチング"
  },
  {
    "id": "move:0131",
    "label": "こうごうせい"
  },
  {
    "id": "move:0132",
    "label": "こうそくいどう"
  },
  {
    "id": "move:0133",
    "label": "こうそくスピン"
  },
  {
    "id": "move:0134",
    "label": "こおりのいぶき"
  },
  {
    "id": "move:0135",
    "label": "こおりのキバ"
  },
  {
    "id": "move:0136",
    "label": "こおりのつぶて"
  },
  {
    "id": "move:0137",
    "label": "こごえるかぜ"
  },
  {
    "id": "move:0138",
    "label": "コスモパワー"
  },
  {
    "id": "move:0139",
    "label": "コットンガード"
  },
  {
    "id": "move:0140",
    "label": "このゆびとまれ"
  },
  {
    "id": "move:0141",
    "label": "コメットパンチ"
  },
  {
    "id": "move:0142",
    "label": "こらえる"
  },
  {
    "id": "move:0143",
    "label": "こわいかお"
  },
  {
    "id": "move:0144",
    "label": "ゴーストダイブ"
  },
  {
    "id": "move:0145",
    "label": "ゴールドラッシュ"
  },
  {
    "id": "move:0146",
    "label": "ゴッドバード"
  },
  {
    "id": "move:0147",
    "label": "サイコカッター"
  },
  {
    "id": "move:0148",
    "label": "サイコキネシス"
  },
  {
    "id": "move:0149",
    "label": "サイコショック"
  },
  {
    "id": "move:0150",
    "label": "サイコノイズ"
  },
  {
    "id": "move:0151",
    "label": "サイコファング"
  },
  {
    "id": "move:0152",
    "label": "サイコフィールド"
  },
  {
    "id": "move:0153",
    "label": "サイドチェンジ"
  },
  {
    "id": "move:0154",
    "label": "さいはい"
  },
  {
    "id": "move:0155",
    "label": "さいみんじゅつ"
  },
  {
    "id": "move:0156",
    "label": "さきおくり"
  },
  {
    "id": "move:0157",
    "label": "さむいギャグ"
  },
  {
    "id": "move:0158",
    "label": "さわぐ"
  },
  {
    "id": "move:0159",
    "label": "サンダーダイブ"
  },
  {
    "id": "move:0160",
    "label": "シェルアームズ"
  },
  {
    "id": "move:0161",
    "label": "シェルブレード"
  },
  {
    "id": "move:0162",
    "label": "しおづけ"
  },
  {
    "id": "move:0163",
    "label": "しおふき"
  },
  {
    "id": "move:0164",
    "label": "シザークロス"
  },
  {
    "id": "move:0165",
    "label": "しっとのほのお"
  },
  {
    "id": "move:0166",
    "label": "しっぺがえし"
  },
  {
    "id": "move:0167",
    "label": "しっぽきり"
  },
  {
    "id": "move:0168",
    "label": "しねんのずつき"
  },
  {
    "id": "move:0169",
    "label": "しびれごな"
  },
  {
    "id": "move:0170",
    "label": "しめつける"
  },
  {
    "id": "move:0171",
    "label": "シャカシャカほう"
  },
  {
    "id": "move:0172",
    "label": "シャドークロー"
  },
  {
    "id": "move:0173",
    "label": "シャドーパンチ"
  },
  {
    "id": "move:0174",
    "label": "シャドーボール"
  },
  {
    "id": "move:0175",
    "label": "しんくうは"
  },
  {
    "id": "move:0176",
    "label": "しんそく"
  },
  {
    "id": "move:0177",
    "label": "しんぴのまもり"
  },
  {
    "id": "move:0178",
    "label": "シンプルビーム"
  },
  {
    "id": "move:0179",
    "label": "Gのちから"
  },
  {
    "id": "move:0180",
    "label": "ジェットパンチ"
  },
  {
    "id": "move:0181",
    "label": "じこあんじ"
  },
  {
    "id": "move:0182",
    "label": "じこさいせい"
  },
  {
    "id": "move:0183",
    "label": "じごくづき"
  },
  {
    "id": "move:0184",
    "label": "じしん"
  },
  {
    "id": "move:0185",
    "label": "じたばた"
  },
  {
    "id": "move:0186",
    "label": "じだんだ"
  },
  {
    "id": "move:0187",
    "label": "じならし"
  },
  {
    "id": "move:0188",
    "label": "じばく"
  },
  {
    "id": "move:0189",
    "label": "じばそうさ"
  },
  {
    "id": "move:0190",
    "label": "ジャイロボール"
  },
  {
    "id": "move:0191",
    "label": "じゃれつく"
  },
  {
    "id": "move:0192",
    "label": "じゅうでん"
  },
  {
    "id": "move:0193",
    "label": "10まんばりき"
  },
  {
    "id": "move:0194",
    "label": "10まんボルト"
  },
  {
    "id": "move:0195",
    "label": "じゅうりょく"
  },
  {
    "id": "move:0196",
    "label": "じわれ"
  },
  {
    "id": "move:0197",
    "label": "じんつうりき"
  },
  {
    "id": "move:0198",
    "label": "スイープビンタ"
  },
  {
    "id": "move:0199",
    "label": "スキルスワップ"
  },
  {
    "id": "move:0200",
    "label": "スケイルショット"
  },
  {
    "id": "move:0201",
    "label": "スケイルノイズ"
  },
  {
    "id": "move:0202",
    "label": "すてゼリフ"
  },
  {
    "id": "move:0203",
    "label": "すてみタックル"
  },
  {
    "id": "move:0204",
    "label": "ステルスロック"
  },
  {
    "id": "move:0205",
    "label": "ストーンエッジ"
  },
  {
    "id": "move:0206",
    "label": "すなあらし"
  },
  {
    "id": "move:0207",
    "label": "すなじごく"
  },
  {
    "id": "move:0208",
    "label": "スピードスワップ"
  },
  {
    "id": "move:0209",
    "label": "スマートホーン"
  },
  {
    "id": "move:0210",
    "label": "すりかえ"
  },
  {
    "id": "move:0211",
    "label": "せいちょう"
  },
  {
    "id": "move:0212",
    "label": "せいなるつるぎ"
  },
  {
    "id": "move:0213",
    "label": "ぜったいれいど"
  },
  {
    "id": "move:0214",
    "label": "ソーラービーム"
  },
  {
    "id": "move:0215",
    "label": "ソーラーブレード"
  },
  {
    "id": "move:0216",
    "label": "そうでん"
  },
  {
    "id": "move:0217",
    "label": "ソウルクラッシュ"
  },
  {
    "id": "move:0218",
    "label": "ソウルビート"
  },
  {
    "id": "move:0219",
    "label": "そらをとぶ"
  },
  {
    "id": "move:0220",
    "label": "たきのぼり"
  },
  {
    "id": "move:0221",
    "label": "たくわえる"
  },
  {
    "id": "move:0222",
    "label": "たたりめ"
  },
  {
    "id": "move:0223",
    "label": "たてこもる"
  },
  {
    "id": "move:0224",
    "label": "タネばくだん"
  },
  {
    "id": "move:0225",
    "label": "タネマシンガン"
  },
  {
    "id": "move:0226",
    "label": "だいちのちから"
  },
  {
    "id": "move:0227",
    "label": "だいちのはどう"
  },
  {
    "id": "move:0228",
    "label": "だいばくはつ"
  },
  {
    "id": "move:0229",
    "label": "ダイビング"
  },
  {
    "id": "move:0230",
    "label": "だいふんげき"
  },
  {
    "id": "move:0231",
    "label": "だいもんじ"
  },
  {
    "id": "move:0232",
    "label": "だくりゅう"
  },
  {
    "id": "move:0233",
    "label": "ダストシュート"
  },
  {
    "id": "move:0234",
    "label": "ダブルアタック"
  },
  {
    "id": "move:0235",
    "label": "ダブルウイング"
  },
  {
    "id": "move:0236",
    "label": "ダメおし"
  },
  {
    "id": "move:0237",
    "label": "ちいさくなる"
  },
  {
    "id": "move:0238",
    "label": "ちからをすいとる"
  },
  {
    "id": "move:0239",
    "label": "ちきゅうなげ"
  },
  {
    "id": "move:0240",
    "label": "チャージビーム"
  },
  {
    "id": "move:0241",
    "label": "ちょうのまい"
  },
  {
    "id": "move:0242",
    "label": "ちょうはつ"
  },
  {
    "id": "move:0243",
    "label": "ついばむ"
  },
  {
    "id": "move:0244",
    "label": "ツインビーム"
  },
  {
    "id": "move:0245",
    "label": "つきのひかり"
  },
  {
    "id": "move:0246",
    "label": "つけあがる"
  },
  {
    "id": "move:0247",
    "label": "つじぎり"
  },
  {
    "id": "move:0248",
    "label": "つのドリル"
  },
  {
    "id": "move:0249",
    "label": "つばめがえし"
  },
  {
    "id": "move:0250",
    "label": "つぶらなひとみ"
  },
  {
    "id": "move:0251",
    "label": "つぼをつく"
  },
  {
    "id": "move:0252",
    "label": "つららおとし"
  },
  {
    "id": "move:0253",
    "label": "つららばり"
  },
  {
    "id": "move:0254",
    "label": "つるぎのまい"
  },
  {
    "id": "move:0255",
    "label": "てだすけ"
  },
  {
    "id": "move:0256",
    "label": "てっていこうせん"
  },
  {
    "id": "move:0257",
    "label": "てっぺき"
  },
  {
    "id": "move:0258",
    "label": "てんしのキッス"
  },
  {
    "id": "move:0259",
    "label": "であいがしら"
  },
  {
    "id": "move:0260",
    "label": "DDラリアット"
  },
  {
    "id": "move:0261",
    "label": "デカハンマー"
  },
  {
    "id": "move:0262",
    "label": "デコレーション"
  },
  {
    "id": "move:0263",
    "label": "でんこうせっか"
  },
  {
    "id": "move:0264",
    "label": "でんじは"
  },
  {
    "id": "move:0265",
    "label": "でんじふゆう"
  },
  {
    "id": "move:0266",
    "label": "でんじほう"
  },
  {
    "id": "move:0267",
    "label": "トーチカ"
  },
  {
    "id": "move:0268",
    "label": "とおせんぼう"
  },
  {
    "id": "move:0269",
    "label": "とおぼえ"
  },
  {
    "id": "move:0270",
    "label": "とぐろをまく"
  },
  {
    "id": "move:0271",
    "label": "とける"
  },
  {
    "id": "move:0272",
    "label": "とっておき"
  },
  {
    "id": "move:0273",
    "label": "とどめばり"
  },
  {
    "id": "move:0274",
    "label": "とびかかる"
  },
  {
    "id": "move:0275",
    "label": "とびつく"
  },
  {
    "id": "move:0276",
    "label": "とびはねる"
  },
  {
    "id": "move:0277",
    "label": "とびひざげり"
  },
  {
    "id": "move:0278",
    "label": "ともえなげ"
  },
  {
    "id": "move:0279",
    "label": "トライアタック"
  },
  {
    "id": "move:0280",
    "label": "トラバサミ"
  },
  {
    "id": "move:0281",
    "label": "トリック"
  },
  {
    "id": "move:0282",
    "label": "トリックフラワー"
  },
  {
    "id": "move:0283",
    "label": "トリックルーム"
  },
  {
    "id": "move:0284",
    "label": "トリプルアクセル"
  },
  {
    "id": "move:0285",
    "label": "トロピカルキック"
  },
  {
    "id": "move:0286",
    "label": "とんぼがえり"
  },
  {
    "id": "move:0287",
    "label": "どくづき"
  },
  {
    "id": "move:0288",
    "label": "どくどく"
  },
  {
    "id": "move:0289",
    "label": "どくどくのキバ"
  },
  {
    "id": "move:0290",
    "label": "どくのいと"
  },
  {
    "id": "move:0291",
    "label": "どくのこな"
  },
  {
    "id": "move:0292",
    "label": "どくばりセンボン"
  },
  {
    "id": "move:0293",
    "label": "どくびし"
  },
  {
    "id": "move:0294",
    "label": "ドゲザン"
  },
  {
    "id": "move:0295",
    "label": "ドラゴンアロー"
  },
  {
    "id": "move:0296",
    "label": "ドラゴンエール"
  },
  {
    "id": "move:0297",
    "label": "ドラゴンクロー"
  },
  {
    "id": "move:0298",
    "label": "ドラゴンダイブ"
  },
  {
    "id": "move:0299",
    "label": "ドラゴンテール"
  },
  {
    "id": "move:0300",
    "label": "ドリルくちばし"
  },
  {
    "id": "move:0301",
    "label": "ドリルライナー"
  },
  {
    "id": "move:0302",
    "label": "ドレインキッス"
  },
  {
    "id": "move:0303",
    "label": "ドレインパンチ"
  },
  {
    "id": "move:0304",
    "label": "どろかけ"
  },
  {
    "id": "move:0305",
    "label": "どろぼう"
  },
  {
    "id": "move:0306",
    "label": "ドわすれ"
  },
  {
    "id": "move:0307",
    "label": "ナイトバースト"
  },
  {
    "id": "move:0308",
    "label": "ナイトヘッド"
  },
  {
    "id": "move:0309",
    "label": "なかまづくり"
  },
  {
    "id": "move:0310",
    "label": "なげつける"
  },
  {
    "id": "move:0311",
    "label": "なまける"
  },
  {
    "id": "move:0312",
    "label": "なみだめ"
  },
  {
    "id": "move:0313",
    "label": "なみのり"
  },
  {
    "id": "move:0314",
    "label": "なやみのタネ"
  },
  {
    "id": "move:0315",
    "label": "なりきり"
  },
  {
    "id": "move:0316",
    "label": "ニードルガード"
  },
  {
    "id": "move:0317",
    "label": "ニトロチャージ"
  },
  {
    "id": "move:0318",
    "label": "にほんばれ"
  },
  {
    "id": "move:0319",
    "label": "ねがいごと"
  },
  {
    "id": "move:0320",
    "label": "ねこだまし"
  },
  {
    "id": "move:0321",
    "label": "ねごと"
  },
  {
    "id": "move:0322",
    "label": "ネズミざん"
  },
  {
    "id": "move:0323",
    "label": "ねっさのだいち"
  },
  {
    "id": "move:0324",
    "label": "ねっとう"
  },
  {
    "id": "move:0325",
    "label": "ねっぷう"
  },
  {
    "id": "move:0326",
    "label": "ねばねばネット"
  },
  {
    "id": "move:0327",
    "label": "ねむりごな"
  },
  {
    "id": "move:0328",
    "label": "ねむる"
  },
  {
    "id": "move:0329",
    "label": "ねをはる"
  },
  {
    "id": "move:0330",
    "label": "のしかかり"
  },
  {
    "id": "move:0331",
    "label": "のみこむ"
  },
  {
    "id": "move:0332",
    "label": "のろい"
  },
  {
    "id": "move:0333",
    "label": "ハードプラント"
  },
  {
    "id": "move:0334",
    "label": "ハードプレス"
  },
  {
    "id": "move:0335",
    "label": "はいすいのじん"
  },
  {
    "id": "move:0336",
    "label": "ハイドロカノン"
  },
  {
    "id": "move:0337",
    "label": "ハイドロポンプ"
  },
  {
    "id": "move:0338",
    "label": "ハイパーボイス"
  },
  {
    "id": "move:0339",
    "label": "はいよるいちげき"
  },
  {
    "id": "move:0340",
    "label": "はかいこうせん"
  },
  {
    "id": "move:0341",
    "label": "はがねのつばさ"
  },
  {
    "id": "move:0342",
    "label": "はきだす"
  },
  {
    "id": "move:0343",
    "label": "ハサミギロチン"
  },
  {
    "id": "move:0344",
    "label": "はたきおとす"
  },
  {
    "id": "move:0345",
    "label": "はたく"
  },
  {
    "id": "move:0346",
    "label": "はどうだん"
  },
  {
    "id": "move:0347",
    "label": "はなびらのまい"
  },
  {
    "id": "move:0348",
    "label": "はなふぶき"
  },
  {
    "id": "move:0349",
    "label": "はねやすめ"
  },
  {
    "id": "move:0350",
    "label": "ハバネロエキス"
  },
  {
    "id": "move:0351",
    "label": "はめつのひかり"
  },
  {
    "id": "move:0352",
    "label": "はやてがえし"
  },
  {
    "id": "move:0353",
    "label": "はらだいこ"
  },
  {
    "id": "move:0354",
    "label": "ハロウィン"
  },
  {
    "id": "move:0355",
    "label": "バークアウト"
  },
  {
    "id": "move:0356",
    "label": "ばかぢから"
  },
  {
    "id": "move:0357",
    "label": "ばくおんぱ"
  },
  {
    "id": "move:0358",
    "label": "ばくれつパンチ"
  },
  {
    "id": "move:0359",
    "label": "バトンタッチ"
  },
  {
    "id": "move:0360",
    "label": "バリアーラッシュ"
  },
  {
    "id": "move:0361",
    "label": "バレットパンチ"
  },
  {
    "id": "move:0362",
    "label": "パラボラチャージ"
  },
  {
    "id": "move:0363",
    "label": "パワーウィップ"
  },
  {
    "id": "move:0364",
    "label": "パワーシェア"
  },
  {
    "id": "move:0365",
    "label": "パワージェム"
  },
  {
    "id": "move:0366",
    "label": "パワースワップ"
  },
  {
    "id": "move:0367",
    "label": "パワートリック"
  },
  {
    "id": "move:0368",
    "label": "ヒートスタンプ"
  },
  {
    "id": "move:0369",
    "label": "ひかりのかべ"
  },
  {
    "id": "move:0370",
    "label": "ひけん・ちえなみ"
  },
  {
    "id": "move:0371",
    "label": "ひっくりかえす"
  },
  {
    "id": "move:0372",
    "label": "ひゃっきやこう"
  },
  {
    "id": "move:0373",
    "label": "ひやみず"
  },
  {
    "id": "move:0374",
    "label": "ひょうざんおろし"
  },
  {
    "id": "move:0375",
    "label": "ビルドアップ"
  },
  {
    "id": "move:0376",
    "label": "ファストガード"
  },
  {
    "id": "move:0377",
    "label": "ふいうち"
  },
  {
    "id": "move:0378",
    "label": "ふういん"
  },
  {
    "id": "move:0379",
    "label": "フェアリーロック"
  },
  {
    "id": "move:0380",
    "label": "フェイタルクロー"
  },
  {
    "id": "move:0381",
    "label": "フェイント"
  },
  {
    "id": "move:0382",
    "label": "フェザーダンス"
  },
  {
    "id": "move:0383",
    "label": "ふきとばし"
  },
  {
    "id": "move:0384",
    "label": "ふくろだたき"
  },
  {
    "id": "move:0385",
    "label": "ふしょくガス"
  },
  {
    "id": "move:0386",
    "label": "ふぶき"
  },
  {
    "id": "move:0387",
    "label": "フライングプレス"
  },
  {
    "id": "move:0388",
    "label": "フラフラダンス"
  },
  {
    "id": "move:0389",
    "label": "フリーズドライ"
  },
  {
    "id": "move:0390",
    "label": "フレアソング"
  },
  {
    "id": "move:0391",
    "label": "フレアドライブ"
  },
  {
    "id": "move:0392",
    "label": "ふんえん"
  },
  {
    "id": "move:0393",
    "label": "ふんか"
  },
  {
    "id": "move:0394",
    "label": "ふんどのこぶし"
  },
  {
    "id": "move:0395",
    "label": "ぶきみなじゅもん"
  },
  {
    "id": "move:0396",
    "label": "ぶちかまし"
  },
  {
    "id": "move:0397",
    "label": "ブラストバーン"
  },
  {
    "id": "move:0398",
    "label": "ブレイククロー"
  },
  {
    "id": "move:0399",
    "label": "ブレイズキック"
  },
  {
    "id": "move:0400",
    "label": "ブレイブバード"
  },
  {
    "id": "move:0401",
    "label": "ぶんまわす"
  },
  {
    "id": "move:0402",
    "label": "ヘドロウェーブ"
  },
  {
    "id": "move:0403",
    "label": "ヘドロばくだん"
  },
  {
    "id": "move:0404",
    "label": "ヘビーボンバー"
  },
  {
    "id": "move:0405",
    "label": "へびにらみ"
  },
  {
    "id": "move:0406",
    "label": "へんしん"
  },
  {
    "id": "move:0407",
    "label": "ベノムショック"
  },
  {
    "id": "move:0408",
    "label": "ほうでん"
  },
  {
    "id": "move:0409",
    "label": "ほうふく"
  },
  {
    "id": "move:0410",
    "label": "ほえる"
  },
  {
    "id": "move:0411",
    "label": "ほおばる"
  },
  {
    "id": "move:0412",
    "label": "ほしがる"
  },
  {
    "id": "move:0413",
    "label": "ほっぺすりすり"
  },
  {
    "id": "move:0414",
    "label": "ほのおのうず"
  },
  {
    "id": "move:0415",
    "label": "ほのおのキバ"
  },
  {
    "id": "move:0416",
    "label": "ほのおのパンチ"
  },
  {
    "id": "move:0417",
    "label": "ほのおのまい"
  },
  {
    "id": "move:0418",
    "label": "ほのおのムチ"
  },
  {
    "id": "move:0419",
    "label": "ほろびのうた"
  },
  {
    "id": "move:0420",
    "label": "ボーンラッシュ"
  },
  {
    "id": "move:0421",
    "label": "ぼうふう"
  },
  {
    "id": "move:0422",
    "label": "ボディプレス"
  },
  {
    "id": "move:0423",
    "label": "ボルテッカー"
  },
  {
    "id": "move:0424",
    "label": "ボルトチェンジ"
  },
  {
    "id": "move:0425",
    "label": "ポルターガイスト"
  },
  {
    "id": "move:0426",
    "label": "まきつく"
  },
  {
    "id": "move:0427",
    "label": "まきびし"
  },
  {
    "id": "move:0428",
    "label": "マジカルシャイン"
  },
  {
    "id": "move:0429",
    "label": "マジカルフレイム"
  },
  {
    "id": "move:0430",
    "label": "マジックルーム"
  },
  {
    "id": "move:0431",
    "label": "マッドショット"
  },
  {
    "id": "move:0432",
    "label": "マッハパンチ"
  },
  {
    "id": "move:0433",
    "label": "まとわりつく"
  },
  {
    "id": "move:0434",
    "label": "まねっこ"
  },
  {
    "id": "move:0435",
    "label": "まほうのこな"
  },
  {
    "id": "move:0436",
    "label": "まもる"
  },
  {
    "id": "move:0437",
    "label": "みがわり"
  },
  {
    "id": "move:0438",
    "label": "みきり"
  },
  {
    "id": "move:0439",
    "label": "ミサイルばり"
  },
  {
    "id": "move:0440",
    "label": "ミストバースト"
  },
  {
    "id": "move:0441",
    "label": "ミストフィールド"
  },
  {
    "id": "move:0442",
    "label": "みずあめボム"
  },
  {
    "id": "move:0443",
    "label": "みずしゅりけん"
  },
  {
    "id": "move:0444",
    "label": "みずのはどう"
  },
  {
    "id": "move:0445",
    "label": "みずびたし"
  },
  {
    "id": "move:0446",
    "label": "みちづれ"
  },
  {
    "id": "move:0447",
    "label": "ミラーコート"
  },
  {
    "id": "move:0448",
    "label": "ミラータイプ"
  },
  {
    "id": "move:0449",
    "label": "みらいよち"
  },
  {
    "id": "move:0450",
    "label": "みわくのボイス"
  },
  {
    "id": "move:0451",
    "label": "ムーンフォース"
  },
  {
    "id": "move:0452",
    "label": "むしくい"
  },
  {
    "id": "move:0453",
    "label": "むしのさざめき"
  },
  {
    "id": "move:0454",
    "label": "むしのていこう"
  },
  {
    "id": "move:0455",
    "label": "むねんのつるぎ"
  },
  {
    "id": "move:0456",
    "label": "めいそう"
  },
  {
    "id": "move:0457",
    "label": "メガトンキック"
  },
  {
    "id": "move:0458",
    "label": "メガホーン"
  },
  {
    "id": "move:0459",
    "label": "メタルバースト"
  },
  {
    "id": "move:0460",
    "label": "メテオビーム"
  },
  {
    "id": "move:0461",
    "label": "メロメロ"
  },
  {
    "id": "move:0462",
    "label": "もえつきる"
  },
  {
    "id": "move:0463",
    "label": "もりののろい"
  },
  {
    "id": "move:0464",
    "label": "もろはのずつき"
  },
  {
    "id": "move:0465",
    "label": "やけっぱち"
  },
  {
    "id": "move:0466",
    "label": "やどりぎのタネ"
  },
  {
    "id": "move:0467",
    "label": "やまあらし"
  },
  {
    "id": "move:0468",
    "label": "ゆきげしき"
  },
  {
    "id": "move:0469",
    "label": "ゆきなだれ"
  },
  {
    "id": "move:0470",
    "label": "ライジングボルト"
  },
  {
    "id": "move:0471",
    "label": "ラスターカノン"
  },
  {
    "id": "move:0472",
    "label": "リーフストーム"
  },
  {
    "id": "move:0473",
    "label": "リーフブレード"
  },
  {
    "id": "move:0474",
    "label": "リサイクル"
  },
  {
    "id": "move:0475",
    "label": "リフレクター"
  },
  {
    "id": "move:0476",
    "label": "りゅうせいぐん"
  },
  {
    "id": "move:0477",
    "label": "りゅうのはどう"
  },
  {
    "id": "move:0478",
    "label": "りゅうのまい"
  },
  {
    "id": "move:0479",
    "label": "りんごさん"
  },
  {
    "id": "move:0480",
    "label": "りんしょう"
  },
  {
    "id": "move:0481",
    "label": "ルミナコリジョン"
  },
  {
    "id": "move:0482",
    "label": "レイジングブル"
  },
  {
    "id": "move:0483",
    "label": "れいとうパンチ"
  },
  {
    "id": "move:0484",
    "label": "れいとうビーム"
  },
  {
    "id": "move:0485",
    "label": "れんごく"
  },
  {
    "id": "move:0486",
    "label": "ローキック"
  },
  {
    "id": "move:0487",
    "label": "ロックオン"
  },
  {
    "id": "move:0488",
    "label": "ロックカット"
  },
  {
    "id": "move:0489",
    "label": "ロックブラスト"
  },
  {
    "id": "move:0490",
    "label": "ワイドガード"
  },
  {
    "id": "move:0491",
    "label": "ワイドフォース"
  },
  {
    "id": "move:0492",
    "label": "ワイドブレイカー"
  },
  {
    "id": "move:0493",
    "label": "ワイルドボルト"
  },
  {
    "id": "move:0494",
    "label": "わたほうし"
  },
  {
    "id": "move:0495",
    "label": "わるあがき"
  },
  {
    "id": "move:0496",
    "label": "わるだくみ"
  },
  {
    "id": "move:0497",
    "label": "ワンダールーム"
  }
];

export const BATTLE_DICTIONARY = {
  pokemon: POKEMON_NAME_DICTIONARY,
  moves: MOVE_NAME_DICTIONARY,
} as const;
